#!/usr/bin/env bash
# [Input] Dream/Admin topology environment variables.
# [Output] Mode-0600 deploy/remote-ssh/.env with public HTTPS service origins.
# [Pos] Alibaba Cloud Dream runtime config generator in deploy/remote-ssh/.
# [Sync] 2026-09-16: project exact Admin issuer/resource and separate service/BFF secrets without a PostgreSQL credential.
# [Sync] 2026-09-16: remove Admin PostgreSQL secret projection from Dream deployment.
# [Sync] 2026-08-22: require a separate HTTPS Gateway origin instead of routing
#                    the Gateway client through the HTTP-only Admin service alias.
# [Sync] 2026-08-22: reuse the validated public HTTPS Admin origin for Product
#                    API because its transport contract rejects non-loopback HTTP.
# [Sync] 2026-08-22: require and validate ECS block-device read budgets after a
#                    real Claude turn saturated the system disk and blocked the host.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTPUT_ENV="${DREAM_REMOTE_ENV_FILE:-${SCRIPT_DIR}/.env}"
DREAM_GATEWAY_ORIGIN="${DREAM_GATEWAY_ORIGIN:-}"
DREAM_PRODUCT_ORIGIN="${DREAM_PRODUCT_ORIGIN:-}"
DREAM_ADMIN_SERVICE_CLIENT_ID="${DREAM_ADMIN_SERVICE_CLIENT_ID:-}"
DREAM_ADMIN_SERVICE_SECRET="${DREAM_ADMIN_SERVICE_SECRET:-}"
DREAM_BFF_COOKIE_SECRET="${DREAM_BFF_COOKIE_SECRET:-}"
DREAM_FILE_STORAGE_TYPE="${DREAM_FILE_STORAGE_TYPE:-local}"
DREAM_BACKEND_BLOCK_DEVICE="${DREAM_BACKEND_BLOCK_DEVICE:-}"
DREAM_BACKEND_READ_BPS="${DREAM_BACKEND_READ_BPS:-}"
DREAM_BACKEND_READ_IOPS="${DREAM_BACKEND_READ_IOPS:-}"

err() { printf '[error] %s\n' "$*" >&2; exit 1; }

[[ "${DREAM_GATEWAY_ORIGIN}" =~ ^https://[^/]+(:[0-9]+)?$ ]] || err "DREAM_GATEWAY_ORIGIN must be an exact HTTPS origin."
[[ "${DREAM_PRODUCT_ORIGIN}" =~ ^https://[^/]+(:[0-9]+)?$ ]] || err "DREAM_PRODUCT_ORIGIN must be an exact HTTPS origin."
[[ "${DREAM_ADMIN_SERVICE_CLIENT_ID}" =~ ^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$ ]] || err "DREAM_ADMIN_SERVICE_CLIENT_ID must be a valid registered identifier."
[[ "${#DREAM_ADMIN_SERVICE_SECRET}" -ge 32 && "${DREAM_ADMIN_SERVICE_SECRET}" != *$'\n'* ]] || err "DREAM_ADMIN_SERVICE_SECRET must contain at least 32 bytes on one line."
[[ "${#DREAM_BFF_COOKIE_SECRET}" -ge 32 && "${DREAM_BFF_COOKIE_SECRET}" != *$'\n'* ]] || err "DREAM_BFF_COOKIE_SECRET must contain at least 32 bytes on one line."
[[ "${DREAM_BACKEND_BLOCK_DEVICE}" =~ ^/dev/[A-Za-z0-9._/-]+$ ]] || err "DREAM_BACKEND_BLOCK_DEVICE must be an absolute /dev path."
[[ "${DREAM_BACKEND_READ_BPS}" =~ ^[1-9][0-9]*(b|kb|kib|mb|mib|gb|gib)$ ]] || err "DREAM_BACKEND_READ_BPS must be a positive Compose byte rate such as 32mb."
[[ "${DREAM_BACKEND_READ_IOPS}" =~ ^[1-9][0-9]*$ ]] || err "DREAM_BACKEND_READ_IOPS must be a positive integer."

temp_file="$(mktemp "${SCRIPT_DIR}/.env.XXXXXX")"
trap 'rm -f "${temp_file}"' EXIT
umask 077
{
  printf '# Generated by deploy/remote-ssh/prepare-env.sh. Do not commit.\n'
  printf 'DREAM_GATEWAY_ORIGIN=%s\n' "${DREAM_GATEWAY_ORIGIN%/}"
  printf 'DREAM_PRODUCT_ORIGIN=%s\n' "${DREAM_PRODUCT_ORIGIN}"
  printf 'DREAM_ADMIN_SERVICE_CLIENT_ID=%s\n' "${DREAM_ADMIN_SERVICE_CLIENT_ID}"
  printf 'DREAM_ADMIN_SERVICE_SECRET=%s\n' "${DREAM_ADMIN_SERVICE_SECRET}"
  printf 'DREAM_BFF_COOKIE_SECRET=%s\n' "${DREAM_BFF_COOKIE_SECRET}"
  printf 'DREAM_FILE_STORAGE_TYPE=%s\n' "${DREAM_FILE_STORAGE_TYPE}"
  printf 'DREAM_BACKEND_BLOCK_DEVICE=%s\n' "${DREAM_BACKEND_BLOCK_DEVICE}"
  printf 'DREAM_BACKEND_READ_BPS=%s\n' "${DREAM_BACKEND_READ_BPS}"
  printf 'DREAM_BACKEND_READ_IOPS=%s\n' "${DREAM_BACKEND_READ_IOPS}"
} >"${temp_file}"
chmod 600 "${temp_file}"
mv "${temp_file}" "${OUTPUT_ENV}"
trap - EXIT
printf '[remote-env] Wrote %s with mode 0600; secret values were not printed.\n' "${OUTPUT_ENV}"
