#!/usr/bin/env bash
# [Input] Admin Alibaba env plus Dream/Admin topology environment variables.
# [Output] Mode-0600 deploy/remote-ssh/.env with embedded-PG DSN and public HTTPS service origins.
# [Pos] Alibaba Cloud Dream runtime config generator in deploy/remote-ssh/.
# [Sync] 2026-08-21: derive the DSN for the Admin container's embedded-PG alias
#                    so Dream cannot reuse a mismatched development password.
# [Sync] 2026-08-22: require a separate HTTPS Gateway origin instead of routing
#                    the Gateway client through the HTTP-only Admin service alias.
# [Sync] 2026-08-22: reuse the validated public HTTPS Admin origin for Product
#                    API because its transport contract rejects non-loopback HTTP.
# [Sync] 2026-08-22: require and validate ECS block-device read budgets after a
#                    real Claude turn saturated the system disk and blocked the host.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
OUTPUT_ENV="${DREAM_REMOTE_ENV_FILE:-${SCRIPT_DIR}/.env}"
ADMIN_ENV_FILE="${DREAM_ADMIN_ENV_FILE:-}"
DREAM_DATABASE_AUTHORITY="${DREAM_DATABASE_AUTHORITY:-ink-memory-postgres:5432}"
DREAM_GATEWAY_ORIGIN="${DREAM_GATEWAY_ORIGIN:-}"
DREAM_PRODUCT_ORIGIN="${DREAM_PRODUCT_ORIGIN:-}"
DREAM_FILE_STORAGE_TYPE="${DREAM_FILE_STORAGE_TYPE:-local}"
DREAM_BACKEND_BLOCK_DEVICE="${DREAM_BACKEND_BLOCK_DEVICE:-}"
DREAM_BACKEND_READ_BPS="${DREAM_BACKEND_READ_BPS:-}"
DREAM_BACKEND_READ_IOPS="${DREAM_BACKEND_READ_IOPS:-}"

err() { printf '[error] %s\n' "$*" >&2; exit 1; }

[[ -n "${ADMIN_ENV_FILE}" ]] || err "DREAM_ADMIN_ENV_FILE is required."
[[ -f "${ADMIN_ENV_FILE}" ]] || err "Missing Admin env: ${ADMIN_ENV_FILE}"
[[ -n "${DREAM_GATEWAY_ORIGIN}" ]] || err "DREAM_GATEWAY_ORIGIN is required."
[[ "${DREAM_GATEWAY_ORIGIN}" == https://* ]] || err "DREAM_GATEWAY_ORIGIN must use https://"
[[ -n "${DREAM_PRODUCT_ORIGIN}" ]] || err "DREAM_PRODUCT_ORIGIN is required."
[[ "${DREAM_PRODUCT_ORIGIN}" == https://* ]] || err "DREAM_PRODUCT_ORIGIN must use https://"
[[ "${DREAM_BACKEND_BLOCK_DEVICE}" =~ ^/dev/[A-Za-z0-9._/-]+$ ]] || err "DREAM_BACKEND_BLOCK_DEVICE must be an absolute /dev path."
[[ "${DREAM_BACKEND_READ_BPS}" =~ ^[1-9][0-9]*(b|kb|kib|mb|mib|gb|gib)$ ]] || err "DREAM_BACKEND_READ_BPS must be a positive Compose byte rate such as 32mb."
[[ "${DREAM_BACKEND_READ_IOPS}" =~ ^[1-9][0-9]*$ ]] || err "DREAM_BACKEND_READ_IOPS must be a positive integer."

database_user="$(awk -F= '$1 == "POSTGRES_USER" { print substr($0, index($0, "=") + 1); exit }' "${ADMIN_ENV_FILE}")"
database_password="$(awk -F= '$1 == "POSTGRES_PASSWORD" { print substr($0, index($0, "=") + 1); exit }' "${ADMIN_ENV_FILE}")"
database_name="$(awk -F= '$1 == "POSTGRES_DB" { print substr($0, index($0, "=") + 1); exit }' "${ADMIN_ENV_FILE}")"
[[ "${database_user}" =~ ^[A-Za-z0-9_]+$ ]] || err "Admin POSTGRES_USER is missing or unsupported."
[[ "${database_password}" =~ ^[A-Za-z0-9._~-]+$ ]] || err "Admin POSTGRES_PASSWORD must be URL-safe."
[[ "${database_name}" =~ ^[A-Za-z0-9_-]+$ ]] || err "Admin POSTGRES_DB is missing or unsupported."
database_url="postgresql://${database_user}:${database_password}@${DREAM_DATABASE_AUTHORITY}/${database_name}"

temp_file="$(mktemp "${SCRIPT_DIR}/.env.XXXXXX")"
trap 'rm -f "${temp_file}"' EXIT
umask 077
{
  printf '# Generated by deploy/remote-ssh/prepare-env.sh. Do not commit.\n'
  printf 'DREAM_DATABASE_URL=%s\n' "${database_url}"
  printf 'DREAM_GATEWAY_ORIGIN=%s\n' "${DREAM_GATEWAY_ORIGIN%/}"
  printf 'DREAM_PRODUCT_ORIGIN=%s\n' "${DREAM_PRODUCT_ORIGIN}"
  printf 'DREAM_FILE_STORAGE_TYPE=%s\n' "${DREAM_FILE_STORAGE_TYPE}"
  printf 'DREAM_BACKEND_BLOCK_DEVICE=%s\n' "${DREAM_BACKEND_BLOCK_DEVICE}"
  printf 'DREAM_BACKEND_READ_BPS=%s\n' "${DREAM_BACKEND_READ_BPS}"
  printf 'DREAM_BACKEND_READ_IOPS=%s\n' "${DREAM_BACKEND_READ_IOPS}"
} >"${temp_file}"
chmod 600 "${temp_file}"
mv "${temp_file}" "${OUTPUT_ENV}"
trap - EXIT
printf '[remote-env] Wrote %s with mode 0600; secret values were not printed.\n' "${OUTPUT_ENV}"
