-- Generated by backend/script/render_postgres_schema.py.
-- Legacy schema manifest sha256: 827dd786d10594c52325ede4cd4dc08487e3cbea3297b55516523386f0d4893c
-- Source inventory: 43 main + 5 Notion; 567 columns; 78 source explicit indexes; 25 triggers.
-- PostgreSQL target: 48 tables; 569 columns; 81 explicit indexes; 25 triggers.
-- Target delta is the approved Admin-head canonical baseline (two deprecated status columns, JSONB settings, and current indexes).
-- Ordinary CREATE is mandatory; only Alembic may adopt the three canonical tables.

-- Wave 1
CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  email TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  display_name TEXT,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  avatar_url TEXT,
  role TEXT DEFAULT 'user' NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  status TEXT DEFAULT 'active' NOT NULL,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_status_check CHECK (status IN ('active', 'disabled'))
);

CREATE TABLE story_workspace_workspaces (
  id TEXT NOT NULL,
  name TEXT NOT NULL,
  owner_id BIGINT NOT NULL,
  settings JSONB DEFAULT '{}'::jsonb NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  status TEXT DEFAULT 'active' NOT NULL,
  CONSTRAINT story_workspace_workspaces_pkey PRIMARY KEY (id),
  CONSTRAINT story_workspace_workspaces_status_check
    CHECK (status IN ('active', 'archived')),
  CONSTRAINT story_workspace_workspaces_owner_id_users_id_fk
    FOREIGN KEY (owner_id) REFERENCES users (id) ON UPDATE NO ACTION ON DELETE RESTRICT
);

CREATE TABLE story_workspace_stories (
  id TEXT NOT NULL,
  identifier TEXT NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  status TEXT DEFAULT 'draft' NOT NULL,
  review_status TEXT DEFAULT 'pending' NOT NULL,
  type TEXT DEFAULT 'short' NOT NULL,
  content TEXT,
  author_id BIGINT NOT NULL,
  workspace_id TEXT NOT NULL,
  character_count INTEGER DEFAULT 0 NOT NULL,
  scene_count INTEGER DEFAULT 0 NOT NULL,
  agent_generated INTEGER DEFAULT 1 NOT NULL,
  agent_session_id TEXT,
  review_notes TEXT,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  confirmed_at TIMESTAMPTZ,
  published_at TIMESTAMPTZ,
  CONSTRAINT story_workspace_stories_pkey PRIMARY KEY (id),
  CONSTRAINT story_workspace_stories_status_check
    CHECK (status IN ('draft', 'published', 'archived')),
  CONSTRAINT story_workspace_stories_review_status_check
    CHECK (review_status IN ('pending', 'confirmed', 'rejected')),
  CONSTRAINT story_workspace_stories_type_check
    CHECK (type IN ('short', 'long', 'script', 'outline')),
  CONSTRAINT story_workspace_stories_agent_generated_check
    CHECK (agent_generated IN (0, 1)),
  CONSTRAINT story_workspace_stories_character_count_check
    CHECK (character_count >= 0),
  CONSTRAINT story_workspace_stories_scene_count_check
    CHECK (scene_count >= 0),
  CONSTRAINT story_workspace_stories_author_id_users_id_fk
    FOREIGN KEY (author_id) REFERENCES users (id) ON UPDATE NO ACTION ON DELETE RESTRICT,
  CONSTRAINT story_workspace_stories_workspace_id_story_workspace_workspaces_id_fk
    FOREIGN KEY (workspace_id) REFERENCES story_workspace_workspaces (id)
    ON UPDATE NO ACTION ON DELETE RESTRICT
);

CREATE TABLE "auth_sessions" (
  "token" TEXT,
  "user_id" BIGINT NOT NULL,
  "expires_at" TIMESTAMPTZ NOT NULL,
  "created_at" TIMESTAMPTZ DEFAULT now(),
  CONSTRAINT "pk_auth_sessions" PRIMARY KEY ("token"),
  CONSTRAINT "fk_auth_sessions_user_id_users" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "oauth_accounts" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "user_id" BIGINT NOT NULL,
  "provider" TEXT NOT NULL,
  "provider_sub" TEXT NOT NULL,
  "email" TEXT NOT NULL,
  "access_token_encrypted" TEXT,
  "refresh_token_encrypted" TEXT,
  "id_token_encrypted" TEXT,
  "expires_at" TIMESTAMPTZ,
  "created_at" TIMESTAMPTZ DEFAULT now(),
  "updated_at" TIMESTAMPTZ DEFAULT now(),
  CONSTRAINT "pk_oauth_accounts" PRIMARY KEY ("id"),
  CONSTRAINT "uq_oauth_accounts_provider_provider_sub" UNIQUE ("provider", "provider_sub"),
  CONSTRAINT "fk_oauth_accounts_user_id_users" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "refresh_tokens" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "user_id" BIGINT NOT NULL,
  "token_hash" TEXT NOT NULL,
  "expires_at" TIMESTAMPTZ NOT NULL,
  "revoked_at" TIMESTAMPTZ,
  "created_at" TIMESTAMPTZ DEFAULT now(),
  CONSTRAINT "pk_refresh_tokens" PRIMARY KEY ("id"),
  CONSTRAINT "uq_refresh_tokens_token_hash" UNIQUE ("token_hash"),
  CONSTRAINT "fk_refresh_tokens_user_id_users" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "device_authorizations" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "client_id" TEXT NOT NULL,
  "device_code_hash" TEXT NOT NULL,
  "user_code_hash" TEXT NOT NULL,
  "user_id" BIGINT,
  "scope" TEXT,
  "status" TEXT NOT NULL,
  "interval_seconds" INTEGER NOT NULL,
  "last_poll_at" TIMESTAMPTZ,
  "expires_at" TIMESTAMPTZ NOT NULL,
  "approved_at" TIMESTAMPTZ,
  "consumed_at" TIMESTAMPTZ,
  "created_at" TIMESTAMPTZ DEFAULT now(),
  "updated_at" TIMESTAMPTZ DEFAULT now(),
  CONSTRAINT "pk_device_authorizations" PRIMARY KEY ("id"),
  CONSTRAINT "uq_device_authorizations_device_code_hash" UNIQUE ("device_code_hash"),
  CONSTRAINT "uq_device_authorizations_user_code_hash" UNIQUE ("user_code_hash"),
  CONSTRAINT "fk_device_authorizations_user_id_users" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE UNIQUE INDEX users_email_uidx ON users (email);

CREATE INDEX users_status_updated_idx ON users (status, updated_at);

CREATE INDEX story_workspace_workspaces_owner_idx ON story_workspace_workspaces (owner_id);

CREATE INDEX story_workspace_workspaces_status_updated_idx ON story_workspace_workspaces (status, updated_at);

CREATE INDEX story_workspace_stories_author_updated_idx ON story_workspace_stories (author_id, updated_at);

CREATE INDEX story_workspace_stories_workspace_updated_idx ON story_workspace_stories (workspace_id, updated_at);

CREATE INDEX story_workspace_stories_status_updated_idx ON story_workspace_stories (status, updated_at);

CREATE INDEX story_workspace_stories_review_updated_idx ON story_workspace_stories (review_status, updated_at);

CREATE INDEX story_workspace_stories_type_updated_idx ON story_workspace_stories (type, updated_at);

CREATE INDEX story_workspace_stories_title_idx ON story_workspace_stories (title);

CREATE INDEX idx_auth_user ON auth_sessions(user_id);

CREATE INDEX idx_oauth_accounts_email ON oauth_accounts(email);

CREATE INDEX idx_oauth_accounts_user ON oauth_accounts(user_id);

CREATE INDEX idx_refresh_tokens_expires ON refresh_tokens(expires_at);

CREATE INDEX idx_refresh_tokens_user ON refresh_tokens(user_id);

CREATE INDEX idx_device_authorizations_device_code_hash ON device_authorizations(device_code_hash);

CREATE INDEX idx_device_authorizations_status_expires ON device_authorizations(status, expires_at);

CREATE INDEX idx_device_authorizations_user_code_hash ON device_authorizations(user_code_hash);

-- Wave 2
CREATE TABLE "story_workspace_characters" (
  "id" TEXT,
  "identifier" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "avatar_url" TEXT,
  "identity" TEXT,
  "personality" TEXT,
  "background" TEXT,
  "catchphrase" TEXT,
  "tags" TEXT DEFAULT '[]',
  "notes" TEXT,
  "author_id" BIGINT NOT NULL,
  "workspace_id" TEXT NOT NULL,
  "story_count" INTEGER NOT NULL DEFAULT 0,
  "review_status" TEXT NOT NULL DEFAULT 'pending',
  "agent_generated" INTEGER NOT NULL DEFAULT 1,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "status" TEXT NOT NULL DEFAULT 'active',
  "review_notes" TEXT,
  "confirmed_at" TIMESTAMPTZ,
  "archived_at" TIMESTAMPTZ,
  CONSTRAINT "pk_story_workspace_characters" PRIMARY KEY ("id"),
  CONSTRAINT "ck_story_workspace_characters_1" CHECK (review_status IN ('pending', 'confirmed', 'rejected')),
  CONSTRAINT "ck_story_workspace_characters_2" CHECK (agent_generated IN (0, 1)),
  CONSTRAINT "ck_story_workspace_characters_3" CHECK (status IN ('active', 'archived')),
  CONSTRAINT "ck_story_workspace_characters_4" CHECK (review_notes IS NULL OR length(review_notes) <= 2000),
  CONSTRAINT "fk_story_workspace_characters_workspace_id_story_wor_1f0a2c1d1f" FOREIGN KEY ("workspace_id") REFERENCES "story_workspace_workspaces" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "fk_story_workspace_characters_author_id_users" FOREIGN KEY ("author_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE "story_workspace_scenes" (
  "id" TEXT,
  "identifier" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "description" TEXT,
  "story_id" TEXT,
  "author_id" BIGINT NOT NULL,
  "workspace_id" TEXT NOT NULL,
  "character_count" INTEGER NOT NULL DEFAULT 0,
  "order_index" INTEGER NOT NULL DEFAULT 0,
  "review_status" TEXT NOT NULL DEFAULT 'pending',
  "agent_generated" INTEGER NOT NULL DEFAULT 1,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "status" TEXT NOT NULL DEFAULT 'active',
  "review_notes" TEXT,
  "confirmed_at" TIMESTAMPTZ,
  "archived_at" TIMESTAMPTZ,
  CONSTRAINT "pk_story_workspace_scenes" PRIMARY KEY ("id"),
  CONSTRAINT "ck_story_workspace_scenes_1" CHECK (review_status IN ('pending', 'confirmed', 'rejected')),
  CONSTRAINT "ck_story_workspace_scenes_2" CHECK (agent_generated IN (0, 1)),
  CONSTRAINT "ck_story_workspace_scenes_3" CHECK (status IN ('active', 'archived')),
  CONSTRAINT "ck_story_workspace_scenes_4" CHECK (review_notes IS NULL OR length(review_notes) <= 2000),
  CONSTRAINT "fk_story_workspace_scenes_workspace_id_story_workspa_a3ba763515" FOREIGN KEY ("workspace_id") REFERENCES "story_workspace_workspaces" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "fk_story_workspace_scenes_author_id_users" FOREIGN KEY ("author_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "fk_story_workspace_scenes_story_id_story_workspace_stories" FOREIGN KEY ("story_id") REFERENCES "story_workspace_stories" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE "story_workspace_story_characters" (
  "story_id" TEXT NOT NULL,
  "character_id" TEXT NOT NULL,
  "role_type" TEXT,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT "pk_story_workspace_story_characters" PRIMARY KEY ("story_id", "character_id"),
  CONSTRAINT "fk_story_workspace_story_characters_character_id_sto_ae8cd95f92" FOREIGN KEY ("character_id") REFERENCES "story_workspace_characters" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "fk_story_workspace_story_characters_story_id_story_w_a3972b6cb6" FOREIGN KEY ("story_id") REFERENCES "story_workspace_stories" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE "story_workspace_scene_characters" (
  "scene_id" TEXT NOT NULL,
  "character_id" TEXT NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT "pk_story_workspace_scene_characters" PRIMARY KEY ("scene_id", "character_id"),
  CONSTRAINT "fk_story_workspace_scene_characters_character_id_sto_819f0fd871" FOREIGN KEY ("character_id") REFERENCES "story_workspace_characters" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "fk_story_workspace_scene_characters_scene_id_story_w_fe7e4c551d" FOREIGN KEY ("scene_id") REFERENCES "story_workspace_scenes" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE INDEX idx_sw_characters_author ON story_workspace_characters(author_id, updated_at DESC NULLS LAST);

CREATE INDEX idx_sw_characters_name ON story_workspace_characters(name);

CREATE INDEX idx_sw_characters_review ON story_workspace_characters(review_status, updated_at DESC NULLS LAST);

CREATE INDEX idx_sw_scenes_author ON story_workspace_scenes(author_id, updated_at DESC NULLS LAST);

CREATE INDEX idx_sw_scenes_review ON story_workspace_scenes(review_status, updated_at DESC NULLS LAST);

CREATE INDEX idx_sw_scenes_story ON story_workspace_scenes(story_id, order_index);

-- Wave 3
CREATE TABLE "user_preferences" (
  "user_id" BIGINT,
  "voice_configs_json" TEXT,
  "meta_prompt" TEXT,
  "state_config_json" TEXT,
  "selected_state" TEXT,
  "timezone" TEXT,
  "first_login_completed" INTEGER DEFAULT 0,
  "system_config_json" TEXT,
  "updated_at" TIMESTAMPTZ DEFAULT now(),
  CONSTRAINT "pk_user_preferences" PRIMARY KEY ("user_id"),
  CONSTRAINT "fk_user_preferences_user_id_users" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "user_sessions" (
  "id" TEXT,
  "user_id" BIGINT NOT NULL,
  "name" TEXT,
  "editor_state_json" TEXT NOT NULL,
  "labels" TEXT,
  "created_at" TIMESTAMPTZ DEFAULT now(),
  "updated_at" TIMESTAMPTZ DEFAULT now(),
  CONSTRAINT "pk_user_sessions" PRIMARY KEY ("id"),
  CONSTRAINT "fk_user_sessions_user_id_users" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "analysis_reports" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "user_id" BIGINT NOT NULL,
  "report_type" TEXT NOT NULL,
  "report_data_json" TEXT NOT NULL,
  "all_notes_text" TEXT,
  "created_at" TIMESTAMPTZ DEFAULT now(),
  CONSTRAINT "pk_analysis_reports" PRIMARY KEY ("id"),
  CONSTRAINT "fk_analysis_reports_user_id_users" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "daily_pictures" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "user_id" BIGINT NOT NULL,
  "date" TEXT NOT NULL,
  "image_base64" TEXT NOT NULL,
  "prompt" TEXT,
  "thumbnail_base64" TEXT,
  "created_at" TIMESTAMPTZ DEFAULT now(),
  CONSTRAINT "pk_daily_pictures" PRIMARY KEY ("id"),
  CONSTRAINT "fk_daily_pictures_user_id_users" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "friend_invites" (
  "code" TEXT,
  "user_id" BIGINT NOT NULL,
  "expires_at" TIMESTAMPTZ NOT NULL,
  "used_by" BIGINT,
  "used_at" TIMESTAMPTZ,
  "created_at" TIMESTAMPTZ DEFAULT now(),
  CONSTRAINT "pk_friend_invites" PRIMARY KEY ("code"),
  CONSTRAINT "fk_friend_invites_used_by_users" FOREIGN KEY ("used_by") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT "fk_friend_invites_user_id_users" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "friendships" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "user_id" BIGINT NOT NULL,
  "friend_id" BIGINT NOT NULL,
  "status" TEXT NOT NULL,
  "created_at" TIMESTAMPTZ DEFAULT now(),
  "updated_at" TIMESTAMPTZ DEFAULT now(),
  CONSTRAINT "pk_friendships" PRIMARY KEY ("id"),
  CONSTRAINT "uq_friendships_user_id_friend_id" UNIQUE ("user_id", "friend_id"),
  CONSTRAINT "ck_friendships_1" CHECK (status IN ('pending', 'accepted', 'rejected')),
  CONSTRAINT "fk_friendships_friend_id_users" FOREIGN KEY ("friend_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "fk_friendships_user_id_users" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE INDEX idx_sessions_user ON user_sessions(user_id);

CREATE INDEX idx_reports_user ON analysis_reports(user_id, created_at);

CREATE INDEX idx_pictures_user_date ON daily_pictures(user_id, date);

CREATE INDEX idx_invites_expires ON friend_invites(expires_at);

CREATE INDEX idx_invites_user ON friend_invites(user_id);

CREATE INDEX idx_friendships_friend ON friendships(friend_id, status);

CREATE INDEX idx_friendships_user ON friendships(user_id, status);

-- Wave 4
CREATE TABLE "reflections_section_configs" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "user_id" BIGINT NOT NULL,
  "section" TEXT NOT NULL,
  "prompt_files" TEXT NOT NULL DEFAULT '{}',
  "updated_at" TIMESTAMPTZ DEFAULT now(),
  CONSTRAINT "pk_reflections_section_configs" PRIMARY KEY ("id"),
  CONSTRAINT "uq_reflections_section_configs_user_id_section" UNIQUE ("user_id", "section"),
  CONSTRAINT "ck_reflections_section_configs_1" CHECK (section IN ('echoes', 'traits', 'patterns')),
  CONSTRAINT "fk_reflections_section_configs_user_id_users" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "reflection_task" (
  "id" TEXT,
  "user_id" BIGINT NOT NULL,
  "status" TEXT NOT NULL,
  "sections" TEXT NOT NULL DEFAULT '[]',
  "input_snapshot" TEXT NOT NULL DEFAULT '{}',
  "workspace_path" TEXT,
  "agent_contract_version" TEXT,
  "error_summary" TEXT,
  "created_at" TIMESTAMPTZ DEFAULT now(),
  "started_at" TIMESTAMPTZ,
  "completed_at" TIMESTAMPTZ,
  "updated_at" TIMESTAMPTZ DEFAULT now(),
  CONSTRAINT "pk_reflection_task" PRIMARY KEY ("id"),
  CONSTRAINT "fk_reflection_task_user_id_users" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "reflection_result" (
  "id" TEXT,
  "task_id" TEXT NOT NULL,
  "user_id" BIGINT NOT NULL,
  "section" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "description" TEXT NOT NULL,
  "related_session_ids" TEXT NOT NULL DEFAULT '[]',
  "evidence" TEXT,
  "confidence" TEXT NOT NULL,
  "created_at" TIMESTAMPTZ DEFAULT now(),
  CONSTRAINT "pk_reflection_result" PRIMARY KEY ("id"),
  CONSTRAINT "ck_reflection_result_1" CHECK (section IN ('echoes', 'traits', 'patterns')),
  CONSTRAINT "ck_reflection_result_2" CHECK (confidence IN ('high', 'medium', 'low')),
  CONSTRAINT "fk_reflection_result_user_id_users" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "fk_reflection_result_task_id_reflection_task" FOREIGN KEY ("task_id") REFERENCES "reflection_task" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "reflection_task_event" (
  "id" TEXT,
  "task_id" TEXT NOT NULL,
  "sequence" INTEGER,
  "event_type" TEXT NOT NULL,
  "payload" TEXT NOT NULL DEFAULT '{}',
  "created_at" TIMESTAMPTZ DEFAULT now(),
  CONSTRAINT "pk_reflection_task_event" PRIMARY KEY ("id"),
  CONSTRAINT "fk_reflection_task_event_task_id_reflection_task" FOREIGN KEY ("task_id") REFERENCES "reflection_task" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "events" (
  "event_id" TEXT,
  "event_type" TEXT NOT NULL,
  "event_version" INTEGER NOT NULL,
  "occurred_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "workspace_id" TEXT NOT NULL,
  "aggregate_id" TEXT NOT NULL,
  "aggregate_version" INTEGER NOT NULL,
  "correlation_id" TEXT NOT NULL,
  "causation_id" TEXT,
  "payload_json" TEXT NOT NULL,
  CONSTRAINT "pk_events" PRIMARY KEY ("event_id"),
  CONSTRAINT "uq_events_aggregate_id_aggregate_version" UNIQUE ("aggregate_id", "aggregate_version"),
  CONSTRAINT "ck_events_1" CHECK (event_version >= 1),
  CONSTRAINT "ck_events_2" CHECK (aggregate_version >= 1)
);

CREATE INDEX idx_reflections_cfg_user ON reflections_section_configs(user_id, section);

CREATE INDEX idx_reflection_task_status ON reflection_task(status);

CREATE INDEX idx_reflection_task_user ON reflection_task(user_id, updated_at);

CREATE INDEX idx_reflection_result_task ON reflection_result(task_id, section);

CREATE INDEX idx_reflection_result_user ON reflection_result(user_id, created_at);

CREATE INDEX idx_reflection_task_event_task ON reflection_task_event(task_id, sequence, created_at);

CREATE INDEX idx_events_aggregate ON events(aggregate_id, aggregate_version);

CREATE INDEX idx_events_correlation ON events(correlation_id);

CREATE INDEX idx_events_type ON events(event_type, occurred_at);

CREATE FUNCTION "dream_guard_events_no_delete"() RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION USING ERRCODE = '55000', MESSAGE = 'events is append-only';
  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER "events_no_delete"
BEFORE DELETE ON "events"
FOR EACH ROW EXECUTE FUNCTION "dream_guard_events_no_delete"();

CREATE FUNCTION "dream_guard_events_no_update"() RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION USING ERRCODE = '55000', MESSAGE = 'events is append-only';
  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER "events_no_update"
BEFORE UPDATE ON "events"
FOR EACH ROW EXECUTE FUNCTION "dream_guard_events_no_update"();

-- Wave 5
CREATE TABLE "decks" (
  "id" TEXT,
  "name" TEXT NOT NULL,
  "name_zh" TEXT,
  "name_en" TEXT,
  "description" TEXT,
  "description_zh" TEXT,
  "description_en" TEXT,
  "icon" TEXT,
  "color" TEXT,
  "is_system" BOOLEAN DEFAULT FALSE,
  "parent_id" TEXT,
  "owner_id" BIGINT,
  "enabled" BOOLEAN DEFAULT TRUE,
  "has_local_changes" BOOLEAN DEFAULT FALSE,
  "order_index" INTEGER,
  "published" BOOLEAN DEFAULT FALSE,
  "author_name" TEXT,
  "install_count" INTEGER DEFAULT 0,
  "created_at" TIMESTAMPTZ DEFAULT now(),
  "updated_at" TIMESTAMPTZ DEFAULT now(),
  CONSTRAINT "pk_decks" PRIMARY KEY ("id"),
  CONSTRAINT "fk_decks_owner_id_users" FOREIGN KEY ("owner_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "fk_decks_parent_id_decks" FOREIGN KEY ("parent_id") REFERENCES "decks" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE "voices" (
  "id" TEXT,
  "deck_id" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "name_zh" TEXT,
  "name_en" TEXT,
  "system_prompt" TEXT NOT NULL,
  "icon" TEXT,
  "color" TEXT,
  "is_system" BOOLEAN DEFAULT FALSE,
  "parent_id" TEXT,
  "owner_id" BIGINT,
  "enabled" BOOLEAN DEFAULT TRUE,
  "has_local_changes" BOOLEAN DEFAULT FALSE,
  "order_index" INTEGER,
  "created_at" TIMESTAMPTZ DEFAULT now(),
  "updated_at" TIMESTAMPTZ DEFAULT now(),
  "thread_id" TEXT,
  "memory_workspace_config" TEXT,
  CONSTRAINT "pk_voices" PRIMARY KEY ("id"),
  CONSTRAINT "fk_voices_owner_id_users" FOREIGN KEY ("owner_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "fk_voices_parent_id_voices" FOREIGN KEY ("parent_id") REFERENCES "voices" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "fk_voices_deck_id_decks" FOREIGN KEY ("deck_id") REFERENCES "decks" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "chat_thread" (
  "id" TEXT,
  "user_id" BIGINT NOT NULL,
  "title" TEXT,
  "deck_id" TEXT,
  "voice_id" TEXT,
  "claude_session_id" TEXT,
  "agent_contract_version" TEXT,
  "created_at" TIMESTAMPTZ DEFAULT now(),
  "updated_at" TIMESTAMPTZ DEFAULT now(),
  CONSTRAINT "pk_chat_thread" PRIMARY KEY ("id"),
  CONSTRAINT "fk_chat_thread_voice_id_voices" FOREIGN KEY ("voice_id") REFERENCES "voices" ("id") ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT "fk_chat_thread_deck_id_decks" FOREIGN KEY ("deck_id") REFERENCES "decks" ("id") ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT "fk_chat_thread_user_id_users" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "chat_message" (
  "id" TEXT,
  "thread_id" TEXT NOT NULL,
  "role" TEXT NOT NULL,
  "parts" TEXT NOT NULL DEFAULT '[]',
  "metadata" TEXT,
  "created_at" TIMESTAMPTZ DEFAULT now(),
  CONSTRAINT "pk_chat_message" PRIMARY KEY ("id"),
  CONSTRAINT "ck_chat_message_1" CHECK (role IN ('user', 'assistant')),
  CONSTRAINT "fk_chat_message_thread_id_chat_thread" FOREIGN KEY ("thread_id") REFERENCES "chat_thread" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "workflow_preflights" (
  "workflow_preflight_id" TEXT,
  "request_fingerprint" TEXT NOT NULL,
  "deck_id" TEXT NOT NULL,
  "binding_revision" INTEGER NOT NULL,
  "deck_plugin_id" TEXT NOT NULL,
  "deck_plugin_version" TEXT NOT NULL,
  "runtime_plugin_lock_id" TEXT NOT NULL,
  "deck_runtime_profile_id" TEXT NOT NULL,
  "deck_runtime_snapshot_id" TEXT,
  "deck_runtime_snapshot_summary_hash" TEXT,
  "input_hash" TEXT NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'checking',
  "error_code" TEXT,
  "failed_check" TEXT,
  "expires_at" TIMESTAMPTZ NOT NULL,
  "preflight_token_hash" TEXT,
  "consumed_at" TIMESTAMPTZ,
  "created_by" TEXT NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT "pk_workflow_preflights" PRIMARY KEY ("workflow_preflight_id"),
  CONSTRAINT "uq_workflow_preflights_preflight_token_hash" UNIQUE ("preflight_token_hash"),
  CONSTRAINT "ck_workflow_preflights_1" CHECK (binding_revision >= 0),
  CONSTRAINT "ck_workflow_preflights_2" CHECK (status IN ('checking', 'passed', 'failed', 'expired')),
  CONSTRAINT "ck_workflow_preflights_3" CHECK ((status = 'failed' AND error_code IS NOT NULL AND failed_check IS NOT NULL)
        OR
        (status != 'failed' AND error_code IS NULL AND failed_check IS NULL))
);

CREATE TABLE "deck_plugin_releases" (
  "id" TEXT,
  "deck_plugin_id" TEXT NOT NULL,
  "deck_plugin_version" TEXT NOT NULL,
  "display_name" TEXT NOT NULL,
  "description" TEXT,
  "author" TEXT,
  "status" TEXT NOT NULL DEFAULT 'draft',
  "manifest_json" TEXT NOT NULL,
  "manifest_hash" TEXT NOT NULL,
  "workflow_definition_ref" TEXT NOT NULL,
  "input_schema_ref" TEXT,
  "output_schema_ref" TEXT,
  "capabilities_json" TEXT,
  "compatibility_json" TEXT,
  "deck_runtime_contract_json" TEXT,
  "runtime_spec_json" TEXT,
  "dependencies_json" TEXT,
  "created_at" TIMESTAMPTZ DEFAULT now(),
  "updated_at" TIMESTAMPTZ DEFAULT now(),
  "published_at" TIMESTAMPTZ,
  CONSTRAINT "pk_deck_plugin_releases" PRIMARY KEY ("id"),
  CONSTRAINT "uq_deck_plugin_releases_deck_plugin_id_deck_plugin_version" UNIQUE ("deck_plugin_id", "deck_plugin_version"),
  CONSTRAINT "ck_deck_plugin_releases_1" CHECK (status IN ('draft', 'validating', 'published', 'deprecated', 'revoked'))
);

CREATE TABLE "deck_runtime_plugin_locks" (
  "id" TEXT,
  "deck_plugin_id" TEXT NOT NULL,
  "deck_plugin_version" TEXT NOT NULL,
  "deck_plugin_manifest_hash" TEXT NOT NULL,
  "lock_json" TEXT NOT NULL,
  "created_at" TIMESTAMPTZ DEFAULT now(),
  CONSTRAINT "pk_deck_runtime_plugin_locks" PRIMARY KEY ("id"),
  CONSTRAINT "uq_deck_runtime_plugin_locks_deck_plugin_id_deck_plugin_version" UNIQUE ("deck_plugin_id", "deck_plugin_version"),
  CONSTRAINT "fk_deck_runtime_plugin_locks_deck_plugin_id_deck_plu_21d73d18c4" FOREIGN KEY ("deck_plugin_id", "deck_plugin_version") REFERENCES "deck_plugin_releases" ("deck_plugin_id", "deck_plugin_version") ON UPDATE NO ACTION ON DELETE RESTRICT
);

CREATE TABLE "deck_plugin_installations" (
  "id" TEXT,
  "scope_type" TEXT NOT NULL,
  "scope_id" TEXT NOT NULL,
  "deck_plugin_id" TEXT NOT NULL,
  "installed_versions_json" TEXT NOT NULL DEFAULT '[]',
  "default_version" TEXT,
  "status" TEXT NOT NULL DEFAULT 'installing',
  "approved_capabilities_json" TEXT NOT NULL DEFAULT '[]',
  "source_policy_id" TEXT NOT NULL,
  "last_error_code" TEXT,
  "last_error_summary" TEXT,
  "pending_version" TEXT,
  "pending_capabilities_json" TEXT,
  "revision" INTEGER NOT NULL DEFAULT 0,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT "pk_deck_plugin_installations" PRIMARY KEY ("id"),
  CONSTRAINT "uq_deck_plugin_installations_scope_type_scope_id_deck_plugin_id" UNIQUE ("scope_type", "scope_id", "deck_plugin_id"),
  CONSTRAINT "ck_deck_plugin_installations_1" CHECK (scope_type IN ('instance', 'workspace')),
  CONSTRAINT "ck_deck_plugin_installations_2" CHECK (status IN (
          'installing', 'ready', 'disabled', 'error',
          'upgrade_pending', 'uninstalled'
        ))
);

CREATE TABLE "deck_plugin_bindings" (
  "deck_plugin_binding_id" TEXT,
  "deck_id" TEXT NOT NULL,
  "workspace_id" TEXT NOT NULL,
  "creator_id" TEXT NOT NULL,
  "deck_plugin_id" TEXT NOT NULL,
  "deck_plugin_version" TEXT NOT NULL,
  "binding_revision" INTEGER NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'active',
  "applied_to" TEXT NOT NULL DEFAULT 'next_run',
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT "pk_deck_plugin_bindings" PRIMARY KEY ("deck_plugin_binding_id"),
  CONSTRAINT "uq_deck_plugin_bindings_deck_id_binding_revision" UNIQUE ("deck_id", "binding_revision"),
  CONSTRAINT "ck_deck_plugin_bindings_1" CHECK (binding_revision >= 1),
  CONSTRAINT "ck_deck_plugin_bindings_2" CHECK (status IN ('active', 'stale')),
  CONSTRAINT "ck_deck_plugin_bindings_3" CHECK (applied_to = 'next_run'),
  CONSTRAINT "fk_deck_plugin_bindings_deck_plugin_id_deck_plugin_v_a1157cb86d" FOREIGN KEY ("deck_plugin_id", "deck_plugin_version") REFERENCES "deck_plugin_releases" ("deck_plugin_id", "deck_plugin_version") ON UPDATE NO ACTION ON DELETE RESTRICT,
  CONSTRAINT "fk_deck_plugin_bindings_deck_id_decks" FOREIGN KEY ("deck_id") REFERENCES "decks" ("id") ON UPDATE NO ACTION ON DELETE RESTRICT
);

CREATE TABLE "deck_runtime_snapshots" (
  "deck_runtime_snapshot_id" TEXT,
  "deck_id" TEXT NOT NULL,
  "deck_plugin_binding_id" TEXT NOT NULL,
  "binding_revision" INTEGER NOT NULL,
  "deck_runtime_profile_id" TEXT NOT NULL,
  "snapshot_contract" TEXT NOT NULL,
  "config_hash" TEXT NOT NULL,
  "config_json" TEXT NOT NULL,
  "sanitized_summary_hash" TEXT NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT "pk_deck_runtime_snapshots" PRIMARY KEY ("deck_runtime_snapshot_id"),
  CONSTRAINT "uq_deck_runtime_snapshots_deck_id_binding_revision_d_e296063f78" UNIQUE ("deck_id", "binding_revision", "deck_runtime_profile_id", "config_hash"),
  CONSTRAINT "ck_deck_runtime_snapshots_1" CHECK (binding_revision >= 1),
  CONSTRAINT "fk_deck_runtime_snapshots_deck_plugin_binding_id_dec_d1ea8e3a21" FOREIGN KEY ("deck_plugin_binding_id") REFERENCES "deck_plugin_bindings" ("deck_plugin_binding_id") ON UPDATE NO ACTION ON DELETE RESTRICT,
  CONSTRAINT "fk_deck_runtime_snapshots_deck_id_decks" FOREIGN KEY ("deck_id") REFERENCES "decks" ("id") ON UPDATE NO ACTION ON DELETE RESTRICT
);

CREATE TABLE "workflow_runs" (
  "id" TEXT,
  "workspace_id" TEXT NOT NULL,
  "deck_plugin_id" TEXT NOT NULL,
  "deck_plugin_version" TEXT NOT NULL,
  "workflow_definition_ref" TEXT NOT NULL,
  "deck_runtime_snapshot_id" TEXT NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'preflight',
  "failed_step" TEXT,
  "error_code" TEXT,
  "retry_of_run_id" TEXT,
  "deck_plugin_manifest_hash" TEXT NOT NULL,
  "deck_plugin_binding_id" TEXT NOT NULL,
  "binding_revision" INTEGER NOT NULL,
  "runtime_plugin_lock_id" TEXT NOT NULL,
  "runtime_load_receipt_id" TEXT,
  "workflow_preflight_id" TEXT NOT NULL,
  "agent_session_id" TEXT,
  "source_voice_thread_id" TEXT,
  "source_message_id" TEXT,
  "source_message_time" TIMESTAMPTZ,
  "idempotency_key" TEXT NOT NULL,
  "input_hash" TEXT NOT NULL,
  "semantic_fingerprint" TEXT NOT NULL,
  "status_version" INTEGER NOT NULL DEFAULT 1,
  "created_by" TEXT NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "started_at" TIMESTAMPTZ,
  "completed_at" TIMESTAMPTZ,
  CONSTRAINT "pk_workflow_runs" PRIMARY KEY ("id"),
  CONSTRAINT "uq_workflow_runs_workspace_id_created_by_idempotency_key" UNIQUE ("workspace_id", "created_by", "idempotency_key"),
  CONSTRAINT "ck_workflow_runs_1" CHECK (status IN (
          'preflight', 'queued', 'running', 'output_validating',
          'pending_review', 'confirmed', 'rejected', 'continuing',
          'completed', 'failed', 'cancelled'
        )),
  CONSTRAINT "ck_workflow_runs_2" CHECK (binding_revision >= 1),
  CONSTRAINT "ck_workflow_runs_3" CHECK (status_version >= 1),
  CONSTRAINT "fk_workflow_runs_workflow_preflight_id_workflow_preflights" FOREIGN KEY ("workflow_preflight_id") REFERENCES "workflow_preflights" ("workflow_preflight_id") ON UPDATE NO ACTION ON DELETE RESTRICT,
  CONSTRAINT "fk_workflow_runs_runtime_plugin_lock_id_deck_runtime_44c881eef2" FOREIGN KEY ("runtime_plugin_lock_id") REFERENCES "deck_runtime_plugin_locks" ("id") ON UPDATE NO ACTION ON DELETE RESTRICT,
  CONSTRAINT "fk_workflow_runs_deck_plugin_binding_id_deck_plugin_bindings" FOREIGN KEY ("deck_plugin_binding_id") REFERENCES "deck_plugin_bindings" ("deck_plugin_binding_id") ON UPDATE NO ACTION ON DELETE RESTRICT,
  CONSTRAINT "fk_workflow_runs_retry_of_run_id_workflow_runs" FOREIGN KEY ("retry_of_run_id") REFERENCES "workflow_runs" ("id") ON UPDATE NO ACTION ON DELETE RESTRICT
);

CREATE TABLE "workflow_run_token_consumptions" (
  "token_digest" TEXT,
  "workflow_run_id" TEXT NOT NULL,
  "workflow_preflight_id" TEXT NOT NULL,
  "workspace_id" TEXT NOT NULL,
  "actor_id" TEXT NOT NULL,
  "idempotency_key" TEXT NOT NULL,
  "semantic_fingerprint" TEXT NOT NULL,
  "consumed_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT "pk_workflow_run_token_consumptions" PRIMARY KEY ("token_digest"),
  CONSTRAINT "fk_workflow_run_token_consumptions_workflow_prefligh_73fad436a7" FOREIGN KEY ("workflow_preflight_id") REFERENCES "workflow_preflights" ("workflow_preflight_id") ON UPDATE NO ACTION ON DELETE RESTRICT,
  CONSTRAINT "fk_workflow_run_token_consumptions_workflow_run_id_w_09114ec819" FOREIGN KEY ("workflow_run_id") REFERENCES "workflow_runs" ("id") ON UPDATE NO ACTION ON DELETE RESTRICT
);

CREATE TABLE "workflow_run_transitions" (
  "id" TEXT,
  "workflow_run_id" TEXT NOT NULL,
  "transition_seq" INTEGER NOT NULL,
  "from_status" TEXT,
  "to_status" TEXT NOT NULL,
  "actor_id" TEXT NOT NULL,
  "reason_code" TEXT,
  "failed_step" TEXT,
  "error_code" TEXT,
  "occurred_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT "pk_workflow_run_transitions" PRIMARY KEY ("id"),
  CONSTRAINT "uq_workflow_run_transitions_workflow_run_id_transition_seq" UNIQUE ("workflow_run_id", "transition_seq"),
  CONSTRAINT "ck_workflow_run_transitions_1" CHECK (transition_seq >= 1),
  CONSTRAINT "fk_workflow_run_transitions_workflow_run_id_workflow_runs" FOREIGN KEY ("workflow_run_id") REFERENCES "workflow_runs" ("id") ON UPDATE NO ACTION ON DELETE RESTRICT
);

CREATE TABLE "runtime_plugin_materializations" (
  "runtime_materialization_id" TEXT,
  "runtime_environment_id" TEXT NOT NULL,
  "runtime_pool_id" TEXT NOT NULL,
  "runtime_node_id" TEXT NOT NULL,
  "claude_code_plugin_id" TEXT NOT NULL,
  "resolved_version" TEXT NOT NULL,
  "artifact_digest" TEXT NOT NULL,
  "materialized_digest" TEXT,
  "artifact_set_hash" TEXT NOT NULL,
  "policy_revision" TEXT NOT NULL,
  "declaration_status" TEXT NOT NULL,
  "materialization_status" TEXT NOT NULL,
  "activation_status" TEXT NOT NULL,
  "materialization_key" TEXT NOT NULL,
  "attempt_id" TEXT NOT NULL,
  "attempt_count" INTEGER NOT NULL,
  "verification_status" TEXT,
  "signature_bundle_ref" TEXT,
  "retention_state" TEXT,
  "restore_source_ref" TEXT,
  "cache_ref" TEXT,
  "last_error" TEXT,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  CONSTRAINT "pk_runtime_plugin_materializations" PRIMARY KEY ("runtime_materialization_id"),
  CONSTRAINT "uq_runtime_plugin_materializations_materialization_key" UNIQUE ("materialization_key"),
  CONSTRAINT "ck_runtime_plugin_materializations_1" CHECK (declaration_status IN ('undeclared', 'declared', 'disabled')),
  CONSTRAINT "ck_runtime_plugin_materializations_2" CHECK (materialization_status IN ('missing', 'materializing', 'materialized', 'failed')),
  CONSTRAINT "ck_runtime_plugin_materializations_3" CHECK (activation_status IN ('inactive', 'loadable', 'loaded', 'load_failed')),
  CONSTRAINT "ck_runtime_plugin_materializations_4" CHECK (attempt_count >= 1),
  CONSTRAINT "ck_runtime_plugin_materializations_5" CHECK (verification_status IS NULL OR verification_status IN ('verified', 'legacy_unverified')),
  CONSTRAINT "ck_runtime_plugin_materializations_6" CHECK (runtime_pool_id = runtime_environment_id)
);

CREATE TABLE "runtime_plugin_reconcile_attempts" (
  "attempt_id" TEXT,
  "workflow_run_id" TEXT,
  "reconcile_path" TEXT NOT NULL,
  "claude_code_plugin_id" TEXT,
  "resolved_version" TEXT,
  "runtime_node_id" TEXT,
  "policy_revision" TEXT NOT NULL,
  "argv_json" TEXT,
  "timeout_seconds" INTEGER,
  "exit_code" INTEGER,
  "stdout_summary" TEXT,
  "stderr_summary" TEXT,
  "result_status" TEXT NOT NULL,
  "error_code" TEXT,
  "created_at" TIMESTAMPTZ NOT NULL,
  CONSTRAINT "pk_runtime_plugin_reconcile_attempts" PRIMARY KEY ("attempt_id"),
  CONSTRAINT "ck_runtime_plugin_reconcile_attempts_1" CHECK (reconcile_path IN ('headless', 'cli')),
  CONSTRAINT "ck_runtime_plugin_reconcile_attempts_2" CHECK (result_status IN ('succeeded', 'failed')),
  CONSTRAINT "fk_runtime_plugin_reconcile_attempts_workflow_run_id_968d500b4b" FOREIGN KEY ("workflow_run_id") REFERENCES "workflow_runs" ("id") ON UPDATE NO ACTION ON DELETE RESTRICT
);

CREATE TABLE "runtime_load_receipts" (
  "receipt_id" TEXT,
  "workflow_run_id" TEXT NOT NULL,
  "runtime_plugin_lock_id" TEXT NOT NULL,
  "runtime_plugin_lock_digest" TEXT NOT NULL,
  "runtime_environment_id" TEXT NOT NULL,
  "runtime_pool_id" TEXT NOT NULL,
  "distribution_mode" TEXT NOT NULL,
  "runtime_node_id" TEXT NOT NULL,
  "artifact_set_hash" TEXT NOT NULL,
  "policy_revision" TEXT NOT NULL,
  "deployment_tier" TEXT NOT NULL,
  "scope" TEXT NOT NULL,
  "readiness_state" TEXT NOT NULL,
  "required_entries_ready" INTEGER NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL,
  CONSTRAINT "pk_runtime_load_receipts" PRIMARY KEY ("receipt_id"),
  CONSTRAINT "ck_runtime_load_receipts_1" CHECK (distribution_mode = 'local_persistent'),
  CONSTRAINT "ck_runtime_load_receipts_2" CHECK (deployment_tier IN ('development', 'test')),
  CONSTRAINT "ck_runtime_load_receipts_3" CHECK (scope = 'session'),
  CONSTRAINT "ck_runtime_load_receipts_4" CHECK (readiness_state = 'session_loaded'),
  CONSTRAINT "ck_runtime_load_receipts_5" CHECK (required_entries_ready IN (0, 1)),
  CONSTRAINT "ck_runtime_load_receipts_6" CHECK (runtime_pool_id = runtime_environment_id),
  CONSTRAINT "fk_runtime_load_receipts_runtime_plugin_lock_id_deck_a3ffee574a" FOREIGN KEY ("runtime_plugin_lock_id") REFERENCES "deck_runtime_plugin_locks" ("id") ON UPDATE NO ACTION ON DELETE RESTRICT,
  CONSTRAINT "fk_runtime_load_receipts_workflow_run_id_workflow_runs" FOREIGN KEY ("workflow_run_id") REFERENCES "workflow_runs" ("id") ON UPDATE NO ACTION ON DELETE RESTRICT
);

CREATE TABLE "runtime_load_receipt_entries" (
  "receipt_id" TEXT NOT NULL,
  "claude_code_plugin_id" TEXT NOT NULL,
  "resolved_version" TEXT NOT NULL,
  "artifact_digest" TEXT NOT NULL,
  "materialized_digest" TEXT NOT NULL,
  "verification_status" TEXT NOT NULL,
  "signature_bundle_ref" TEXT,
  "retention_state" TEXT NOT NULL,
  "restore_source_ref" TEXT,
  "required" INTEGER NOT NULL,
  "loaded_capabilities_json" TEXT NOT NULL,
  "load_status" TEXT NOT NULL,
  "loaded_at" TIMESTAMPTZ NOT NULL,
  CONSTRAINT "pk_runtime_load_receipt_entries" PRIMARY KEY ("receipt_id", "claude_code_plugin_id"),
  CONSTRAINT "ck_runtime_load_receipt_entries_1" CHECK (verification_status IN ('verified', 'legacy_unverified')),
  CONSTRAINT "ck_runtime_load_receipt_entries_2" CHECK (required IN (0, 1)),
  CONSTRAINT "ck_runtime_load_receipt_entries_3" CHECK (load_status IN ('loaded', 'load_failed', 'skipped')),
  CONSTRAINT "fk_runtime_load_receipt_entries_receipt_id_runtime_l_f7f5afca38" FOREIGN KEY ("receipt_id") REFERENCES "runtime_load_receipts" ("receipt_id") ON UPDATE NO ACTION ON DELETE RESTRICT
);

CREATE TABLE "agent_sessions" (
  "agent_session_id" TEXT,
  "workflow_run_id" TEXT NOT NULL,
  "runtime_load_receipt_id" TEXT NOT NULL,
  "runtime_environment_id" TEXT NOT NULL,
  "runtime_pool_id" TEXT NOT NULL,
  "distribution_mode" TEXT NOT NULL,
  "runtime_node_id" TEXT NOT NULL,
  "artifact_set_hash" TEXT NOT NULL,
  "policy_revision" TEXT NOT NULL,
  "deployment_tier" TEXT NOT NULL,
  "runtime_plugin_lock_id" TEXT NOT NULL,
  "runtime_plugin_lock_digest" TEXT NOT NULL,
  "settings_json" TEXT NOT NULL,
  "settings_hash" TEXT NOT NULL,
  "plugin_set_hash" TEXT NOT NULL,
  "session_request_key" TEXT NOT NULL,
  "attempt_number" INTEGER NOT NULL,
  "status" TEXT NOT NULL,
  "error_code" TEXT,
  "termination_reason_code" TEXT,
  "created_at" TIMESTAMPTZ NOT NULL,
  "started_at" TIMESTAMPTZ,
  "terminated_at" TIMESTAMPTZ,
  "lease_expires_at" TIMESTAMPTZ,
  "owner_token" TEXT,
  "remote_session_ref" TEXT,
  CONSTRAINT "pk_agent_sessions" PRIMARY KEY ("agent_session_id"),
  CONSTRAINT "uq_agent_sessions_session_request_key" UNIQUE ("session_request_key"),
  CONSTRAINT "uq_agent_sessions_workflow_run_id_attempt_number" UNIQUE ("workflow_run_id", "attempt_number"),
  CONSTRAINT "ck_agent_sessions_1" CHECK (distribution_mode = 'local_persistent'),
  CONSTRAINT "ck_agent_sessions_2" CHECK (deployment_tier IN ('development', 'test')),
  CONSTRAINT "ck_agent_sessions_3" CHECK (attempt_number >= 1),
  CONSTRAINT "ck_agent_sessions_4" CHECK (status IN ('creating', 'active', 'terminated', 'failed')),
  CONSTRAINT "ck_agent_sessions_5" CHECK (runtime_pool_id = runtime_environment_id),
  CONSTRAINT "fk_agent_sessions_runtime_plugin_lock_id_deck_runtim_d1f3baf217" FOREIGN KEY ("runtime_plugin_lock_id") REFERENCES "deck_runtime_plugin_locks" ("id") ON UPDATE NO ACTION ON DELETE RESTRICT,
  CONSTRAINT "fk_agent_sessions_runtime_load_receipt_id_runtime_load_receipts" FOREIGN KEY ("runtime_load_receipt_id") REFERENCES "runtime_load_receipts" ("receipt_id") ON UPDATE NO ACTION ON DELETE RESTRICT,
  CONSTRAINT "fk_agent_sessions_workflow_run_id_workflow_runs" FOREIGN KEY ("workflow_run_id") REFERENCES "workflow_runs" ("id") ON UPDATE NO ACTION ON DELETE RESTRICT
);

CREATE TABLE "claude_plugin_installations" (
  "id" TEXT,
  "requested_package_spec" TEXT NOT NULL,
  "package_name" TEXT NOT NULL,
  "marketplace" TEXT NOT NULL,
  "requested_version" TEXT,
  "resolved_version" TEXT NOT NULL,
  "source_type" TEXT NOT NULL,
  "artifact_digest" TEXT NOT NULL,
  "artifact_path" TEXT NOT NULL,
  "claude_cli_version" TEXT NOT NULL,
  "cli_git_commit_sha" TEXT,
  "manifest_json" TEXT,
  "component_inventory_json" TEXT NOT NULL DEFAULT '{}',
  "compatibility_json" TEXT NOT NULL DEFAULT '{}',
  "status" TEXT NOT NULL DEFAULT 'installing',
  "operation_id" TEXT NOT NULL,
  "error_code" TEXT,
  "error_summary" TEXT,
  "file_count" INTEGER NOT NULL DEFAULT 0,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "installed_at" TIMESTAMPTZ,
  CONSTRAINT "pk_claude_plugin_installations" PRIMARY KEY ("id"),
  CONSTRAINT "uq_claude_plugin_installations_package_name_marketpl_ea25e21de3" UNIQUE ("package_name", "marketplace", "resolved_version", "artifact_digest"),
  CONSTRAINT "ck_claude_plugin_installations_1" CHECK (source_type IN ('claude-official', 'marketplace', 'github', 'platform-builtin')),
  CONSTRAINT "ck_claude_plugin_installations_2" CHECK (status IN ('installing', 'ready', 'error', 'uninstalled'))
);

CREATE TABLE "claude_plugin_operations" (
  "id" TEXT,
  "operation_kind" TEXT NOT NULL,
  "requested_package_spec" TEXT NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'queued',
  "phase" TEXT NOT NULL DEFAULT 'queued',
  "progress" INTEGER NOT NULL DEFAULT 0,
  "message" TEXT,
  "executable" TEXT,
  "argv_json" TEXT,
  "cwd" TEXT,
  "cli_version" TEXT,
  "exit_code" INTEGER,
  "evidence_path" TEXT,
  "installation_id" TEXT,
  "error_code" TEXT,
  "error_summary" TEXT,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "finished_at" TIMESTAMPTZ,
  CONSTRAINT "pk_claude_plugin_operations" PRIMARY KEY ("id"),
  CONSTRAINT "ck_claude_plugin_operations_1" CHECK (operation_kind IN ('install', 'uninstall', 'validate', 'revalidate')),
  CONSTRAINT "ck_claude_plugin_operations_2" CHECK (status IN ('queued', 'running', 'ready', 'error'))
);

CREATE TABLE "deck_claude_plugin_refs" (
  "deck_id" TEXT NOT NULL,
  "plugin_installation_id" TEXT NOT NULL,
  "package_spec" TEXT NOT NULL,
  "resolved_version" TEXT NOT NULL,
  "artifact_digest" TEXT NOT NULL,
  "enabled" INTEGER NOT NULL DEFAULT 1,
  "order_index" INTEGER NOT NULL DEFAULT 0,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT "pk_deck_claude_plugin_refs" PRIMARY KEY ("deck_id", "plugin_installation_id"),
  CONSTRAINT "fk_deck_claude_plugin_refs_plugin_installation_id_cl_d75be593ed" FOREIGN KEY ("plugin_installation_id") REFERENCES "claude_plugin_installations" ("id") ON UPDATE NO ACTION ON DELETE RESTRICT,
  CONSTRAINT "fk_deck_claude_plugin_refs_deck_id_decks" FOREIGN KEY ("deck_id") REFERENCES "decks" ("id") ON UPDATE NO ACTION ON DELETE RESTRICT
);

CREATE INDEX idx_decks_owner ON decks(owner_id);

CREATE INDEX idx_voices_deck ON voices(deck_id);

CREATE INDEX idx_voices_owner ON voices(owner_id);

CREATE INDEX idx_chat_thread_user ON chat_thread(user_id, updated_at);

CREATE INDEX idx_chat_message_thread ON chat_message(thread_id, created_at);

CREATE UNIQUE INDEX idx_workflow_preflights_active_request ON workflow_preflights(request_fingerprint) WHERE status IN ('checking', 'passed') AND consumed_at IS NULL;

CREATE INDEX idx_workflow_preflights_deck_revision ON workflow_preflights(deck_id, binding_revision);

CREATE INDEX idx_workflow_preflights_status_expiry ON workflow_preflights(status, expires_at);

CREATE INDEX idx_deck_plugin_releases_id_version ON deck_plugin_releases(deck_plugin_id, deck_plugin_version);

CREATE INDEX idx_deck_plugin_releases_status ON deck_plugin_releases(status);

CREATE INDEX idx_runtime_locks_deck_plugin ON deck_runtime_plugin_locks(deck_plugin_id, deck_plugin_version);

CREATE INDEX idx_installations_deck_plugin ON deck_plugin_installations(deck_plugin_id);

CREATE INDEX idx_installations_scope ON deck_plugin_installations(scope_type, scope_id);

CREATE INDEX idx_installations_status ON deck_plugin_installations(status);

CREATE UNIQUE INDEX idx_deck_plugin_bindings_active_deck ON deck_plugin_bindings(deck_id) WHERE status = 'active';

CREATE INDEX idx_deck_plugin_bindings_deck_revision ON deck_plugin_bindings(deck_id, binding_revision DESC NULLS LAST);

CREATE INDEX idx_deck_plugin_bindings_release ON deck_plugin_bindings(deck_plugin_id, deck_plugin_version);

CREATE INDEX idx_deck_plugin_bindings_workspace ON deck_plugin_bindings(workspace_id, updated_at DESC NULLS LAST);

CREATE INDEX idx_deck_runtime_snapshots_deck ON deck_runtime_snapshots(deck_id, binding_revision, created_at DESC NULLS LAST);

CREATE INDEX idx_workflow_runs_deck_plugin ON workflow_runs(deck_plugin_id, deck_plugin_version);

CREATE INDEX idx_workflow_runs_idempotency ON workflow_runs(workspace_id, created_by, idempotency_key);

CREATE INDEX idx_workflow_runs_retry ON workflow_runs(retry_of_run_id);

CREATE INDEX idx_workflow_runs_status ON workflow_runs(status);

CREATE INDEX idx_workflow_run_token_consumptions_run ON workflow_run_token_consumptions(workflow_run_id);

CREATE INDEX idx_workflow_run_transitions_run ON workflow_run_transitions(workflow_run_id, transition_seq);

CREATE INDEX idx_runtime_materializations_lookup ON runtime_plugin_materializations(runtime_environment_id, runtime_node_id, claude_code_plugin_id);

CREATE INDEX idx_runtime_materializations_status ON runtime_plugin_materializations(materialization_status, activation_status);

CREATE INDEX idx_runtime_reconcile_attempts_run ON runtime_plugin_reconcile_attempts(workflow_run_id, created_at);

CREATE INDEX idx_runtime_load_receipts_placement ON runtime_load_receipts(runtime_environment_id, runtime_node_id);

CREATE INDEX idx_runtime_load_receipts_run ON runtime_load_receipts(workflow_run_id, created_at);

CREATE UNIQUE INDEX idx_agent_sessions_one_live_run ON agent_sessions(workflow_run_id) WHERE status IN ('creating', 'active');

CREATE INDEX idx_agent_sessions_run ON agent_sessions(workflow_run_id, attempt_number);

CREATE INDEX idx_claude_plugin_installations_pkg ON claude_plugin_installations(package_name, marketplace);

CREATE INDEX idx_claude_plugin_installations_status ON claude_plugin_installations(status);

CREATE INDEX idx_claude_plugin_operations_status ON claude_plugin_operations(status, created_at);

CREATE INDEX idx_deck_claude_plugin_refs_deck ON deck_claude_plugin_refs(deck_id, enabled, order_index);

CREATE FUNCTION "dream_guard_agent_sessions_immutable_binding"() RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF OLD.agent_session_id IS DISTINCT FROM NEW.agent_session_id
    OR OLD.workflow_run_id IS DISTINCT FROM NEW.workflow_run_id
    OR OLD.runtime_load_receipt_id IS DISTINCT FROM NEW.runtime_load_receipt_id
    OR OLD.runtime_environment_id IS DISTINCT FROM NEW.runtime_environment_id
    OR OLD.runtime_pool_id IS DISTINCT FROM NEW.runtime_pool_id
    OR OLD.distribution_mode IS DISTINCT FROM NEW.distribution_mode
    OR OLD.runtime_node_id IS DISTINCT FROM NEW.runtime_node_id
    OR OLD.artifact_set_hash IS DISTINCT FROM NEW.artifact_set_hash
    OR OLD.policy_revision IS DISTINCT FROM NEW.policy_revision
    OR OLD.deployment_tier IS DISTINCT FROM NEW.deployment_tier
    OR OLD.runtime_plugin_lock_id IS DISTINCT FROM NEW.runtime_plugin_lock_id
    OR OLD.runtime_plugin_lock_digest IS DISTINCT FROM NEW.runtime_plugin_lock_digest
    OR OLD.settings_json IS DISTINCT FROM NEW.settings_json
    OR OLD.settings_hash IS DISTINCT FROM NEW.settings_hash
    OR OLD.plugin_set_hash IS DISTINCT FROM NEW.plugin_set_hash
    OR OLD.session_request_key IS DISTINCT FROM NEW.session_request_key
    OR OLD.attempt_number IS DISTINCT FROM NEW.attempt_number
    OR OLD.created_at IS DISTINCT FROM NEW.created_at THEN
    RAISE EXCEPTION USING ERRCODE = '55000', MESSAGE = 'agent session binding is immutable';
  END IF;
  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER "agent_sessions_immutable_binding"
BEFORE UPDATE ON "agent_sessions"
FOR EACH ROW EXECUTE FUNCTION "dream_guard_agent_sessions_immutable_binding"();

CREATE FUNCTION "dream_guard_agent_sessions_lifecycle_insert_guard"() RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.status != 'creating'
    OR NEW.started_at IS NOT NULL
    OR NEW.terminated_at IS NOT NULL
    OR NEW.error_code IS NOT NULL
    OR NEW.termination_reason_code IS NOT NULL
    OR NEW.lease_expires_at IS NULL THEN
    RAISE EXCEPTION USING ERRCODE = '55000', MESSAGE = 'new agent session must start with a creating lease';
  END IF;
  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER "agent_sessions_lifecycle_insert_guard"
BEFORE INSERT ON "agent_sessions"
FOR EACH ROW EXECUTE FUNCTION "dream_guard_agent_sessions_lifecycle_insert_guard"();

CREATE FUNCTION "dream_guard_agent_sessions_lifecycle_update_guard"() RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF (NEW.status = 'active' AND (
    NEW.started_at IS NULL OR NEW.terminated_at IS NOT NULL
    OR NEW.error_code IS NOT NULL OR NEW.termination_reason_code IS NOT NULL
    ))
    OR (NEW.status = 'terminated' AND (
    NEW.started_at IS NULL OR NEW.terminated_at IS NULL
    OR NEW.error_code IS NOT NULL OR NEW.termination_reason_code IS NULL
    ))
    OR (NEW.status = 'failed' AND (
    NEW.terminated_at IS NULL OR NEW.error_code IS NULL
    OR NEW.termination_reason_code IS NULL
    )) THEN
    RAISE EXCEPTION USING ERRCODE = '55000', MESSAGE = 'agent session lifecycle fields are inconsistent';
  END IF;
  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER "agent_sessions_lifecycle_update_guard"
BEFORE UPDATE ON "agent_sessions"
FOR EACH ROW EXECUTE FUNCTION "dream_guard_agent_sessions_lifecycle_update_guard"();

CREATE FUNCTION "dream_guard_agent_sessions_status_guard"() RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF OLD.status IS DISTINCT FROM NEW.status
    AND NOT (
    (OLD.status = 'creating' AND NEW.status IN ('active', 'failed'))
    OR (OLD.status = 'active' AND NEW.status IN ('terminated', 'failed'))
    ) THEN
    RAISE EXCEPTION USING ERRCODE = '55000', MESSAGE = 'agent session transition is not allowed';
  END IF;
  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER "agent_sessions_status_guard"
BEFORE UPDATE OF STATUS ON "agent_sessions"
FOR EACH ROW EXECUTE FUNCTION "dream_guard_agent_sessions_status_guard"();

CREATE FUNCTION "dream_guard_deck_runtime_snapshots_no_delete"() RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION USING ERRCODE = '55000', MESSAGE = 'deck_runtime_snapshots is append-only';
  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER "deck_runtime_snapshots_no_delete"
BEFORE DELETE ON "deck_runtime_snapshots"
FOR EACH ROW EXECUTE FUNCTION "dream_guard_deck_runtime_snapshots_no_delete"();

CREATE FUNCTION "dream_guard_deck_runtime_snapshots_no_update"() RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION USING ERRCODE = '55000', MESSAGE = 'deck_runtime_snapshots is append-only';
  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER "deck_runtime_snapshots_no_update"
BEFORE UPDATE ON "deck_runtime_snapshots"
FOR EACH ROW EXECUTE FUNCTION "dream_guard_deck_runtime_snapshots_no_update"();

CREATE FUNCTION "dream_guard_runtime_load_receipt_entries_no_delete"() RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION USING ERRCODE = '55000', MESSAGE = 'runtime_load_receipt_entries is append-only';
  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER "runtime_load_receipt_entries_no_delete"
BEFORE DELETE ON "runtime_load_receipt_entries"
FOR EACH ROW EXECUTE FUNCTION "dream_guard_runtime_load_receipt_entries_no_delete"();

CREATE FUNCTION "dream_guard_runtime_load_receipt_entries_no_update"() RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION USING ERRCODE = '55000', MESSAGE = 'runtime_load_receipt_entries is append-only';
  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER "runtime_load_receipt_entries_no_update"
BEFORE UPDATE ON "runtime_load_receipt_entries"
FOR EACH ROW EXECUTE FUNCTION "dream_guard_runtime_load_receipt_entries_no_update"();

CREATE FUNCTION "dream_guard_runtime_load_receipts_no_delete"() RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION USING ERRCODE = '55000', MESSAGE = 'runtime_load_receipts is append-only';
  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER "runtime_load_receipts_no_delete"
BEFORE DELETE ON "runtime_load_receipts"
FOR EACH ROW EXECUTE FUNCTION "dream_guard_runtime_load_receipts_no_delete"();

CREATE FUNCTION "dream_guard_runtime_load_receipts_no_update"() RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION USING ERRCODE = '55000', MESSAGE = 'runtime_load_receipts is append-only';
  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER "runtime_load_receipts_no_update"
BEFORE UPDATE ON "runtime_load_receipts"
FOR EACH ROW EXECUTE FUNCTION "dream_guard_runtime_load_receipts_no_update"();

CREATE FUNCTION "dream_guard_runtime_materializations_immutable_identity"() RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF OLD.runtime_materialization_id IS DISTINCT FROM NEW.runtime_materialization_id
    OR OLD.runtime_environment_id IS DISTINCT FROM NEW.runtime_environment_id
    OR OLD.runtime_pool_id IS DISTINCT FROM NEW.runtime_pool_id
    OR OLD.runtime_node_id IS DISTINCT FROM NEW.runtime_node_id
    OR OLD.claude_code_plugin_id IS DISTINCT FROM NEW.claude_code_plugin_id
    OR OLD.resolved_version IS DISTINCT FROM NEW.resolved_version
    OR OLD.artifact_digest IS DISTINCT FROM NEW.artifact_digest
    OR OLD.artifact_set_hash IS DISTINCT FROM NEW.artifact_set_hash
    OR OLD.policy_revision IS DISTINCT FROM NEW.policy_revision
    OR OLD.materialization_key IS DISTINCT FROM NEW.materialization_key
    OR OLD.created_at IS DISTINCT FROM NEW.created_at THEN
    RAISE EXCEPTION USING ERRCODE = '55000', MESSAGE = 'runtime materialization identity is immutable';
  END IF;
  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER "runtime_materializations_immutable_identity"
BEFORE UPDATE ON "runtime_plugin_materializations"
FOR EACH ROW EXECUTE FUNCTION "dream_guard_runtime_materializations_immutable_identity"();

CREATE FUNCTION "dream_guard_runtime_reconcile_attempts_no_delete"() RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION USING ERRCODE = '55000', MESSAGE = 'runtime_plugin_reconcile_attempts is append-only';
  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER "runtime_reconcile_attempts_no_delete"
BEFORE DELETE ON "runtime_plugin_reconcile_attempts"
FOR EACH ROW EXECUTE FUNCTION "dream_guard_runtime_reconcile_attempts_no_delete"();

CREATE FUNCTION "dream_guard_runtime_reconcile_attempts_no_update"() RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION USING ERRCODE = '55000', MESSAGE = 'runtime_plugin_reconcile_attempts is append-only';
  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER "runtime_reconcile_attempts_no_update"
BEFORE UPDATE ON "runtime_plugin_reconcile_attempts"
FOR EACH ROW EXECUTE FUNCTION "dream_guard_runtime_reconcile_attempts_no_update"();

CREATE FUNCTION "dream_guard_workflow_run_token_consumptions_no_delete"() RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION USING ERRCODE = '55000', MESSAGE = 'workflow_run_token_consumptions is append-only';
  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER "workflow_run_token_consumptions_no_delete"
BEFORE DELETE ON "workflow_run_token_consumptions"
FOR EACH ROW EXECUTE FUNCTION "dream_guard_workflow_run_token_consumptions_no_delete"();

CREATE FUNCTION "dream_guard_workflow_run_token_consumptions_no_update"() RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION USING ERRCODE = '55000', MESSAGE = 'workflow_run_token_consumptions is append-only';
  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER "workflow_run_token_consumptions_no_update"
BEFORE UPDATE ON "workflow_run_token_consumptions"
FOR EACH ROW EXECUTE FUNCTION "dream_guard_workflow_run_token_consumptions_no_update"();

CREATE FUNCTION "dream_guard_workflow_run_transitions_no_delete"() RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION USING ERRCODE = '55000', MESSAGE = 'workflow_run_transitions is append-only';
  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER "workflow_run_transitions_no_delete"
BEFORE DELETE ON "workflow_run_transitions"
FOR EACH ROW EXECUTE FUNCTION "dream_guard_workflow_run_transitions_no_delete"();

CREATE FUNCTION "dream_guard_workflow_run_transitions_no_update"() RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION USING ERRCODE = '55000', MESSAGE = 'workflow_run_transitions is append-only';
  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER "workflow_run_transitions_no_update"
BEFORE UPDATE ON "workflow_run_transitions"
FOR EACH ROW EXECUTE FUNCTION "dream_guard_workflow_run_transitions_no_update"();

CREATE FUNCTION "dream_guard_workflow_runs_immutable_provenance"() RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF OLD.id IS DISTINCT FROM NEW.id
    OR OLD.workspace_id IS DISTINCT FROM NEW.workspace_id
    OR OLD.deck_plugin_id IS DISTINCT FROM NEW.deck_plugin_id
    OR OLD.deck_plugin_version IS DISTINCT FROM NEW.deck_plugin_version
    OR OLD.workflow_definition_ref IS DISTINCT FROM NEW.workflow_definition_ref
    OR OLD.deck_runtime_snapshot_id IS DISTINCT FROM NEW.deck_runtime_snapshot_id
    OR OLD.retry_of_run_id IS DISTINCT FROM NEW.retry_of_run_id
    OR OLD.deck_plugin_manifest_hash IS DISTINCT FROM NEW.deck_plugin_manifest_hash
    OR OLD.deck_plugin_binding_id IS DISTINCT FROM NEW.deck_plugin_binding_id
    OR OLD.binding_revision IS DISTINCT FROM NEW.binding_revision
    OR OLD.runtime_plugin_lock_id IS DISTINCT FROM NEW.runtime_plugin_lock_id
    OR OLD.workflow_preflight_id IS DISTINCT FROM NEW.workflow_preflight_id
    OR OLD.source_voice_thread_id IS DISTINCT FROM NEW.source_voice_thread_id
    OR OLD.idempotency_key IS DISTINCT FROM NEW.idempotency_key
    OR OLD.input_hash IS DISTINCT FROM NEW.input_hash
    OR OLD.semantic_fingerprint IS DISTINCT FROM NEW.semantic_fingerprint
    OR OLD.created_by IS DISTINCT FROM NEW.created_by
    OR OLD.created_at IS DISTINCT FROM NEW.created_at
    OR (
    OLD.runtime_load_receipt_id IS DISTINCT FROM NEW.runtime_load_receipt_id
    AND NOT (
    OLD.runtime_load_receipt_id IS NULL
    AND NEW.runtime_load_receipt_id IS NOT NULL
    AND OLD.status = 'queued'
    AND NEW.status = 'running'
    )
    ) THEN
    RAISE EXCEPTION USING ERRCODE = '55000', MESSAGE = 'workflow run provenance is immutable';
  END IF;
  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER "workflow_runs_immutable_provenance"
BEFORE UPDATE ON "workflow_runs"
FOR EACH ROW EXECUTE FUNCTION "dream_guard_workflow_runs_immutable_provenance"();

CREATE FUNCTION "dream_guard_workflow_runs_joint_session_binding_guard"() RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF (NEW.runtime_load_receipt_id IS NULL) != (NEW.agent_session_id IS NULL)
    OR (
    OLD.runtime_load_receipt_id IS NULL
    AND OLD.agent_session_id IS NULL
    AND NEW.runtime_load_receipt_id IS NOT NULL
    AND NOT (OLD.status = 'queued' AND NEW.status = 'running')
    )
    OR (
    OLD.runtime_load_receipt_id IS NOT NULL
    AND (
    OLD.runtime_load_receipt_id IS DISTINCT FROM NEW.runtime_load_receipt_id
    OR OLD.agent_session_id IS DISTINCT FROM NEW.agent_session_id
    )
    )
    OR (
    NEW.status IN (
    'running', 'output_validating', 'pending_review', 'confirmed',
    'rejected', 'continuing', 'completed'
    )
    AND NEW.runtime_load_receipt_id IS NULL
    )
    OR (
    NEW.status IN ('preflight', 'queued')
    AND NEW.runtime_load_receipt_id IS NOT NULL
    )
    OR (
    NEW.agent_session_id IS NOT NULL
    AND (
    NEW.agent_session_id = NEW.source_voice_thread_id
    OR NEW.agent_session_id = NEW.source_message_id
    )
    )
    OR (
    NEW.agent_session_id IS NOT NULL
    AND OLD.agent_session_id IS NULL
    AND NOT EXISTS (
    SELECT 1 FROM agent_sessions AS session
    WHERE session.agent_session_id = NEW.agent_session_id
    AND session.workflow_run_id = NEW.id
    AND session.runtime_load_receipt_id = NEW.runtime_load_receipt_id
    AND session.runtime_plugin_lock_id = NEW.runtime_plugin_lock_id
    AND session.status = 'active'
    )
    ) THEN
    RAISE EXCEPTION USING ERRCODE = '55000', MESSAGE = 'workflow run receipt and session binding is invalid';
  END IF;
  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER "workflow_runs_joint_session_binding_guard"
BEFORE UPDATE ON "workflow_runs"
FOR EACH ROW EXECUTE FUNCTION "dream_guard_workflow_runs_joint_session_binding_guard"();

CREATE FUNCTION "dream_guard_workflow_runs_runtime_receipt_binding_guard"() RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.runtime_load_receipt_id IS NOT NULL
    AND OLD.runtime_load_receipt_id IS DISTINCT FROM NEW.runtime_load_receipt_id
    AND NOT EXISTS (
    SELECT 1
    FROM runtime_load_receipts AS receipt
    WHERE receipt.receipt_id = NEW.runtime_load_receipt_id
    AND receipt.workflow_run_id = NEW.id
    ) THEN
    RAISE EXCEPTION USING ERRCODE = '55000', MESSAGE = 'runtime load receipt is missing or bound to another run';
  END IF;
  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER "workflow_runs_runtime_receipt_binding_guard"
BEFORE UPDATE OF RUNTIME_LOAD_RECEIPT_ID ON "workflow_runs"
FOR EACH ROW EXECUTE FUNCTION "dream_guard_workflow_runs_runtime_receipt_binding_guard"();

CREATE FUNCTION "dream_guard_workflow_runs_status_version_guard"() RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF (
    OLD.status IS DISTINCT FROM NEW.status
    AND NEW.status_version != OLD.status_version + 1
    ) OR (
    OLD.status IS NOT DISTINCT FROM NEW.status
    AND NEW.status_version != OLD.status_version
    ) THEN
    RAISE EXCEPTION USING ERRCODE = '55000', MESSAGE = 'workflow run status_version mismatch';
  END IF;
  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER "workflow_runs_status_version_guard"
BEFORE UPDATE ON "workflow_runs"
FOR EACH ROW EXECUTE FUNCTION "dream_guard_workflow_runs_status_version_guard"();

CREATE FUNCTION "dream_guard_workflow_runs_voice_source_immutable"() RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF OLD.source_voice_thread_id IS DISTINCT FROM NEW.source_voice_thread_id
    OR OLD.source_message_id IS DISTINCT FROM NEW.source_message_id
    OR OLD.source_message_time IS DISTINCT FROM NEW.source_message_time THEN
    RAISE EXCEPTION USING ERRCODE = '55000', MESSAGE = 'workflow run Voice source is immutable';
  END IF;
  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER "workflow_runs_voice_source_immutable"
BEFORE UPDATE ON "workflow_runs"
FOR EACH ROW EXECUTE FUNCTION "dream_guard_workflow_runs_voice_source_immutable"();

CREATE FUNCTION "dream_guard_workflow_runs_voice_source_insert_guard"() RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF num_nonnulls(NEW.source_voice_thread_id, NEW.source_message_id, NEW.source_message_time) NOT IN (0, 3) THEN
    RAISE EXCEPTION USING ERRCODE = '55000', MESSAGE = 'Voice source requires thread, message, and time';
  END IF;
  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER "workflow_runs_voice_source_insert_guard"
BEFORE INSERT ON "workflow_runs"
FOR EACH ROW EXECUTE FUNCTION "dream_guard_workflow_runs_voice_source_insert_guard"();

-- Wave 6
CREATE TABLE "resource_connectors" (
  "id" TEXT,
  "user_id" BIGINT NOT NULL,
  "name" TEXT NOT NULL,
  "platform" TEXT NOT NULL,
  "auth_status" TEXT NOT NULL DEFAULT 'pending',
  "config_json" TEXT NOT NULL DEFAULT '{}',
  "current_snapshot_version" TEXT,
  "current_source_revision" TEXT,
  "current_sync_cursor" TEXT,
  "last_synced_at" TIMESTAMPTZ,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT "pk_resource_connectors" PRIMARY KEY ("id"),
  CONSTRAINT "fk_resource_connectors_user_id_users" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE RESTRICT
);

CREATE TABLE "connector_resources" (
  "id" TEXT,
  "connector_id" TEXT NOT NULL,
  "resource_type" TEXT NOT NULL,
  "external_id" TEXT,
  "title" TEXT NOT NULL,
  "metadata_json" TEXT NOT NULL DEFAULT '{}',
  "sync_status" TEXT NOT NULL DEFAULT 'synced',
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT "pk_connector_resources" PRIMARY KEY ("id"),
  CONSTRAINT "uq_connector_resources_connector_id_resource_type_external_id" UNIQUE ("connector_id", "resource_type", "external_id"),
  CONSTRAINT "fk_connector_resources_connector_id_resource_connectors" FOREIGN KEY ("connector_id") REFERENCES "resource_connectors" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "connector_resource_pages" (
  "id" TEXT,
  "resource_id" TEXT NOT NULL,
  "page_id" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "last_edited" TIMESTAMPTZ,
  "properties_json" TEXT,
  "page_json" TEXT,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT "pk_connector_resource_pages" PRIMARY KEY ("id"),
  CONSTRAINT "uq_connector_resource_pages_resource_id_page_id" UNIQUE ("resource_id", "page_id"),
  CONSTRAINT "fk_connector_resource_pages_resource_id_connector_resources" FOREIGN KEY ("resource_id") REFERENCES "connector_resources" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "connector_snapshots" (
  "id" TEXT,
  "connector_id" TEXT NOT NULL,
  "snapshot_version" TEXT NOT NULL,
  "source_revision" TEXT NOT NULL,
  "sync_cursor" TEXT NOT NULL,
  "fetched_at" TIMESTAMPTZ NOT NULL,
  "state" TEXT NOT NULL DEFAULT 'snapshot_ready',
  "snapshot_json" TEXT NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT "pk_connector_snapshots" PRIMARY KEY ("id"),
  CONSTRAINT "uq_connector_snapshots_connector_id_snapshot_version" UNIQUE ("connector_id", "snapshot_version"),
  CONSTRAINT "fk_connector_snapshots_connector_id_resource_connectors" FOREIGN KEY ("connector_id") REFERENCES "resource_connectors" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "connector_chat_threads" (
  "id" TEXT,
  "connector_id" TEXT NOT NULL,
  "thread_id" TEXT NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT "pk_connector_chat_threads" PRIMARY KEY ("id"),
  CONSTRAINT "uq_connector_chat_threads_connector_id_thread_id" UNIQUE ("connector_id", "thread_id"),
  CONSTRAINT "fk_connector_chat_threads_connector_id_resource_connectors" FOREIGN KEY ("connector_id") REFERENCES "resource_connectors" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE INDEX idx_resource_connectors_user_updated ON resource_connectors(user_id, updated_at DESC NULLS LAST);

CREATE INDEX idx_connector_resources_connector ON connector_resources(connector_id, resource_type, updated_at DESC NULLS LAST);

CREATE INDEX idx_connector_resource_pages_resource ON connector_resource_pages(resource_id, last_edited DESC NULLS LAST);

CREATE INDEX idx_connector_snapshots_connector ON connector_snapshots(connector_id, created_at DESC NULLS LAST);

CREATE INDEX idx_connector_chat_threads_connector ON connector_chat_threads(connector_id, updated_at DESC NULLS LAST);
