"""Render the checked-in legacy catalog as ordinary PostgreSQL DDL.

The renderer is intentionally offline and deterministic.  It does not connect
to a database and never adds ``IF NOT EXISTS``: collisions outside the three
explicit baseline-adopt tables must abort the migration transaction.
"""

from __future__ import annotations

import hashlib
import re
from typing import Any, Iterable

from .catalog import BASELINE_TABLES, load_manifest


TARGET_EXPLICIT_INDEX_COUNT = 81


BASELINE_TABLE_DDL: dict[str, str] = {
    "users": """
CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  email TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  display_name TEXT,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  avatar_url TEXT,
  role TEXT DEFAULT 'user' NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  status TEXT DEFAULT 'active' NOT NULL,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_status_check CHECK (status IN ('active', 'disabled'))
)
""".strip(),
    "story_workspace_workspaces": """
CREATE TABLE story_workspace_workspaces (
  id TEXT NOT NULL,
  name TEXT NOT NULL,
  owner_id BIGINT NOT NULL,
  settings JSONB DEFAULT '{}'::jsonb NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  status TEXT DEFAULT 'active' NOT NULL,
  CONSTRAINT story_workspace_workspaces_pkey PRIMARY KEY (id),
  CONSTRAINT story_workspace_workspaces_status_check
    CHECK (status IN ('active', 'archived')),
  CONSTRAINT story_workspace_workspaces_owner_id_users_id_fk
    FOREIGN KEY (owner_id) REFERENCES users (id) ON UPDATE NO ACTION ON DELETE RESTRICT
)
""".strip(),
    "story_workspace_stories": """
CREATE TABLE story_workspace_stories (
  id TEXT NOT NULL,
  identifier TEXT NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  status TEXT DEFAULT 'draft' NOT NULL,
  review_status TEXT DEFAULT 'pending' NOT NULL,
  type TEXT DEFAULT 'short' NOT NULL,
  content TEXT,
  author_id BIGINT NOT NULL,
  workspace_id TEXT NOT NULL,
  character_count INTEGER DEFAULT 0 NOT NULL,
  scene_count INTEGER DEFAULT 0 NOT NULL,
  agent_generated INTEGER DEFAULT 1 NOT NULL,
  agent_session_id TEXT,
  review_notes TEXT,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  confirmed_at TIMESTAMPTZ,
  published_at TIMESTAMPTZ,
  CONSTRAINT story_workspace_stories_pkey PRIMARY KEY (id),
  CONSTRAINT story_workspace_stories_status_check
    CHECK (status IN ('draft', 'published', 'archived')),
  CONSTRAINT story_workspace_stories_review_status_check
    CHECK (review_status IN ('pending', 'confirmed', 'rejected')),
  CONSTRAINT story_workspace_stories_type_check
    CHECK (type IN ('short', 'long', 'script', 'outline')),
  CONSTRAINT story_workspace_stories_agent_generated_check
    CHECK (agent_generated IN (0, 1)),
  CONSTRAINT story_workspace_stories_character_count_check
    CHECK (character_count >= 0),
  CONSTRAINT story_workspace_stories_scene_count_check
    CHECK (scene_count >= 0),
  CONSTRAINT story_workspace_stories_author_id_users_id_fk
    FOREIGN KEY (author_id) REFERENCES users (id) ON UPDATE NO ACTION ON DELETE RESTRICT,
  CONSTRAINT story_workspace_stories_workspace_id_story_workspace_workspaces_id_fk
    FOREIGN KEY (workspace_id) REFERENCES story_workspace_workspaces (id)
    ON UPDATE NO ACTION ON DELETE RESTRICT
)
""".strip(),
}


BASELINE_INDEX_DDL: tuple[str, ...] = (
    "CREATE UNIQUE INDEX users_email_uidx ON users (email)",
    "CREATE INDEX users_status_updated_idx ON users (status, updated_at)",
    "CREATE INDEX story_workspace_workspaces_owner_idx ON story_workspace_workspaces (owner_id)",
    "CREATE INDEX story_workspace_workspaces_status_updated_idx ON story_workspace_workspaces (status, updated_at)",
    "CREATE INDEX story_workspace_stories_author_updated_idx ON story_workspace_stories (author_id, updated_at)",
    "CREATE INDEX story_workspace_stories_workspace_updated_idx ON story_workspace_stories (workspace_id, updated_at)",
    "CREATE INDEX story_workspace_stories_status_updated_idx ON story_workspace_stories (status, updated_at)",
    "CREATE INDEX story_workspace_stories_review_updated_idx ON story_workspace_stories (review_status, updated_at)",
    "CREATE INDEX story_workspace_stories_type_updated_idx ON story_workspace_stories (type, updated_at)",
    "CREATE INDEX story_workspace_stories_title_idx ON story_workspace_stories (title)",
)


def _quote(identifier: str) -> str:
    return '"' + identifier.replace('"', '""') + '"'


def _identifier(prefix: str, *parts: str) -> str:
    raw = "_".join((prefix, *parts))
    if len(raw.encode("utf-8")) <= 63:
        return raw
    digest = hashlib.sha256(raw.encode("utf-8")).hexdigest()[:10]
    return raw[: 63 - len(digest) - 1] + "_" + digest


def _default_expression(column: dict[str, Any]) -> str | None:
    default = column.get("default")
    if default is None:
        return None
    value = str(default).strip()
    target_type = column["transform"]["target_type"]
    if value.upper() == "CURRENT_TIMESTAMP":
        return "now()"
    if target_type == "boolean" and value in {"0", "1"}:
        return "FALSE" if value == "0" else "TRUE"
    return value


def render_table_ddl(table: dict[str, Any]) -> str:
    name = str(table["name"])
    if name in BASELINE_TABLE_DDL:
        return BASELINE_TABLE_DDL[name]

    lines: list[str] = []
    for column in table["columns"]:
        transform = column["transform"]
        target_type = str(transform["target_type"]).upper()
        definition = f"{_quote(column['name'])} {target_type}"
        if transform.get("identity"):
            definition += " GENERATED BY DEFAULT AS IDENTITY"
        if column.get("not_null"):
            definition += " NOT NULL"
        default = _default_expression(column)
        if default is not None:
            definition += f" DEFAULT {default}"
        lines.append(definition)

    primary_key = list(table["primary_key"])
    if primary_key:
        constraint_name = _identifier("pk", name)
        columns = ", ".join(_quote(column) for column in primary_key)
        lines.append(f"CONSTRAINT {_quote(constraint_name)} PRIMARY KEY ({columns})")

    for unique in table["unique_checks"]:
        # origin=u is a CREATE TABLE UNIQUE contract.  origin=c is already
        # represented by the ordinary explicit index DDL below.
        if unique["origin"] != "u":
            continue
        columns = list(unique["columns"])
        if not columns:
            raise ValueError(f"unsupported expression UNIQUE constraint on {name}")
        constraint_name = _identifier("uq", name, *columns)
        rendered_columns = ", ".join(_quote(column) for column in columns)
        lines.append(
            f"CONSTRAINT {_quote(constraint_name)} UNIQUE ({rendered_columns})"
        )

    for index, check in enumerate(table["checks"], start=1):
        constraint_name = _identifier("ck", name, str(index))
        lines.append(f"CONSTRAINT {_quote(constraint_name)} CHECK ({check})")

    for foreign_key in table["foreign_keys"]:
        columns = list(foreign_key["columns"])
        target_columns = list(foreign_key["target_columns"])
        constraint_name = _identifier(
            "fk", name, "_".join(columns), str(foreign_key["target_table"])
        )
        rendered_columns = ", ".join(_quote(column) for column in columns)
        rendered_targets = ", ".join(_quote(column) for column in target_columns)
        on_update = str(foreign_key["on_update"])
        on_delete = str(foreign_key["on_delete"])
        lines.append(
            f"CONSTRAINT {_quote(constraint_name)} FOREIGN KEY ({rendered_columns}) "
            f"REFERENCES {_quote(foreign_key['target_table'])} ({rendered_targets}) "
            f"ON UPDATE {on_update} ON DELETE {on_delete}"
        )

    body = ",\n  ".join(lines)
    return f"CREATE TABLE {_quote(name)} (\n  {body}\n)"


def render_index_ddl(index: dict[str, Any]) -> str:
    source = str(index["source_sql"])
    result = re.sub(
        r"\bCREATE\s+(UNIQUE\s+)?INDEX\s+IF\s+NOT\s+EXISTS\s+",
        lambda match: "CREATE " + (match.group(1) or "") + "INDEX ",
        source,
        flags=re.IGNORECASE,
    )
    # SQLite DESC sorts NULL last; PostgreSQL DESC defaults to NULL first.
    result = re.sub(
        r"\bDESC\b(?!\s+NULLS\s+(?:FIRST|LAST))",
        "DESC NULLS LAST",
        result,
        flags=re.IGNORECASE,
    )
    if re.search(r"\bIF\s+NOT\s+EXISTS\b", result, flags=re.IGNORECASE):
        raise ValueError(f"index renderer left drift-masking DDL: {index['name']}")
    return result.strip()


_TRIGGER_PATTERN = re.compile(
    r"^\s*CREATE\s+TRIGGER\s+(?P<name>[A-Za-z0-9_]+)\s+"
    r"BEFORE\s+(?P<event>INSERT|DELETE|UPDATE(?:\s+OF\s+[A-Za-z0-9_,\s]+)?)\s+"
    r"ON\s+(?P<table>[A-Za-z0-9_]+)\s*"
    r"(?:WHEN\s+(?P<condition>.*?))?\s*"
    r"BEGIN\s+SELECT\s+RAISE\(ABORT,\s*'(?P<message>[^']*)'\);\s*END\s*$",
    flags=re.IGNORECASE | re.DOTALL,
)


def _translate_trigger_condition(condition: str) -> str:
    result = re.sub(
        r"\b((?:OLD|NEW)\.[A-Za-z0-9_]+)\s+IS\s+NOT\s+"
        r"((?:OLD|NEW)\.[A-Za-z0-9_]+)\b",
        r"\1 IS DISTINCT FROM \2",
        condition,
        flags=re.IGNORECASE,
    )
    result = re.sub(
        r"\b((?:OLD|NEW)\.[A-Za-z0-9_]+)\s+IS\s+"
        r"((?:OLD|NEW)\.[A-Za-z0-9_]+)\b",
        r"\1 IS NOT DISTINCT FROM \2",
        result,
        flags=re.IGNORECASE,
    )
    result = re.sub(
        r"\(\s*\(NEW\.source_voice_thread_id\s+IS\s+NOT\s+NULL\)\s*\+\s*"
        r"\(NEW\.source_message_id\s+IS\s+NOT\s+NULL\)\s*\+\s*"
        r"\(NEW\.source_message_time\s+IS\s+NOT\s+NULL\)\s*\)\s*"
        r"NOT\s+IN\s*\(0,\s*3\)",
        "num_nonnull(NEW.source_voice_thread_id, NEW.source_message_id, "
        "NEW.source_message_time) NOT IN (0, 3)",
        result,
        flags=re.IGNORECASE | re.DOTALL,
    )
    return "\n    ".join(line.strip() for line in result.strip().splitlines())


def render_trigger_ddl(trigger: dict[str, Any]) -> tuple[str, str]:
    match = _TRIGGER_PATTERN.match(str(trigger["source_sql"]))
    if not match:
        raise ValueError(f"unsupported SQLite trigger syntax: {trigger['name']}")
    function_name = _identifier("dream_guard", str(trigger["name"]))
    message = match.group("message").replace("'", "''")
    condition = match.group("condition")
    if condition:
        guard = (
            f"  IF {_translate_trigger_condition(condition)} THEN\n"
            f"    RAISE EXCEPTION USING ERRCODE = '55000', MESSAGE = '{message}';\n"
            "  END IF;"
        )
    else:
        guard = f"  RAISE EXCEPTION USING ERRCODE = '55000', MESSAGE = '{message}';"
    function_ddl = (
        f"CREATE FUNCTION {_quote(function_name)}() RETURNS trigger\n"
        "LANGUAGE plpgsql\n"
        "AS $$\n"
        "BEGIN\n"
        f"{guard}\n"
        "  IF TG_OP = 'DELETE' THEN\n"
        "    RETURN OLD;\n"
        "  END IF;\n"
        "  RETURN NEW;\n"
        "END;\n"
        "$$"
    )
    trigger_ddl = (
        f"CREATE TRIGGER {_quote(match.group('name'))}\n"
        f"BEFORE {match.group('event').upper()} ON {_quote(match.group('table'))}\n"
        f"FOR EACH ROW EXECUTE FUNCTION {_quote(function_name)}()"
    )
    return function_ddl, trigger_ddl


def table_map(manifest: dict[str, Any] | None = None) -> dict[str, dict[str, Any]]:
    payload = load_manifest() if manifest is None else manifest
    return {str(table["name"]): table for table in payload["tables"]}


def wave_statements(
    wave: int,
    *,
    manifest: dict[str, Any] | None = None,
    include_baseline: bool = True,
) -> list[str]:
    payload = load_manifest() if manifest is None else manifest
    tables_by_name = table_map(payload)
    names = list(payload["waves"][str(wave)])
    if not include_baseline:
        names = [name for name in names if name not in BASELINE_TABLES]
    statements = [render_table_ddl(tables_by_name[name]) for name in names]

    if include_baseline and wave == 1:
        statements.extend(BASELINE_INDEX_DDL)
    for name in names:
        if name in BASELINE_TABLES:
            continue
        statements.extend(
            render_index_ddl(index)
            for index in tables_by_name[name]["explicit_indexes"]
        )

    wave_names = set(names)
    for trigger in payload["triggers"]:
        if trigger["table"] not in wave_names:
            continue
        statements.extend(render_trigger_ddl(trigger))
    return statements


def render_postgres_schema(manifest: dict[str, Any] | None = None) -> str:
    payload = load_manifest() if manifest is None else manifest
    lines = [
        "-- Generated by backend/script/render_postgres_schema.py.",
        f"-- Legacy schema manifest sha256: {payload['catalog_sha256']}",
        "-- Source inventory: 43 main + 5 Notion; 567 columns; 78 source explicit indexes; 25 triggers.",
        "-- PostgreSQL target: 48 tables; 569 columns; 81 explicit indexes; 25 triggers.",
        "-- Target delta is the approved Admin-head canonical baseline (two deprecated status columns, JSONB settings, and current indexes).",
        "-- Ordinary CREATE is mandatory; only Alembic may adopt the three canonical tables.",
        "",
    ]
    for wave in range(1, 7):
        lines.append(f"-- Wave {wave}")
        for statement in wave_statements(wave, manifest=payload):
            lines.append(statement.rstrip() + ";")
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def all_trigger_ddls(manifest: dict[str, Any] | None = None) -> Iterable[tuple[str, str]]:
    payload = load_manifest() if manifest is None else manifest
    for trigger in payload["triggers"]:
        yield render_trigger_ddl(trigger)
