// [Input] Existing dmeck account, normal local Dream/Admin/Gateway/PostgreSQL services, installed Chrome, and a live Claude Runtime.
// [Output] Real-business evidence for Chat schedule creation, persisted marker/sidebar, unattended Editor write, run conversation, ten-minute edit, and pause.
// [Pos] Opt-in real scheduled-task business journey; the named note, task, Threads, Run, Gateway request and logs remain available for review.
// [Sync] 2026-10-07: require an existing public-login storage state; remove direct signing/identity writes, fail immediately on terminal trigger failure, and pause only this run's task.
// [Sync] 2026-10-07: wait for asynchronous New Session reset before filling and match the subsequent save response independently of payload inspection.
// [Sync] 2026-10-07: expand the shared sidebar More group before returning from a run Chat to Writing.
// [Sync] 2026-10-07: verify the opened run chat by the trigger-bound final message ID, avoiding duplicate prompt/result text matches.
// [Sync] 2026-10-07: cover the Codex-style interval task and scheduled per-tool auto/manual policy through public production entry points, pausing only prior named QA tasks.

// @ts-expect-error Playwright E2E uses Node built-ins outside the browser app tsconfig.
import { mkdirSync } from 'node:fs';
// @ts-expect-error Playwright E2E uses Node built-ins outside the browser app tsconfig.
import { resolve } from 'node:path';
import { expect, test, type APIRequestContext, type Page } from '@playwright/test';

const ENABLED = process.env.INK_REAL_SCHEDULED_TASK_QA === '1';
const WEB_BASE = process.env.INK_REAL_SCHEDULED_TASK_WEB_BASE ?? 'http://localhost:5173';
const ACTOR_EMAIL = process.env.INK_REAL_SCHEDULED_TASK_ACTOR_EMAIL ?? 'dmeck@suoxya.com';
// Generated by normal browser login; never create or sign credentials in this test.
const AUTH_STATE = process.env.INK_REAL_SCHEDULED_TASK_STORAGE_STATE;
const ARTIFACT_DIR = resolve(process.cwd(), 'test-results/real-scheduled-task');

type ScheduledRule =
  | { kind: 'once'; local_date: string; local_time: string; time_zone: string; selected_offset_minutes: number | null }
  | { kind: 'daily'; local_time: string; time_zone: string }
  | { kind: 'interval'; interval_minutes: number; time_zone: string };
type ScheduledTask = {
  id: string; source_thread_id: string; title: string; prompt: string; rule: ScheduledRule;
  next_run_at: string | null; status: 'active' | 'paused' | 'exhausted' | 'deleted'; revision: number;
};
type ScheduledTrigger = {
  id: string; status: 'claimed' | 'queued' | 'running' | 'succeeded' | 'failed' | 'state_unknown' | 'skipped';
  target_thread_id: string | null; final_message_id: string | null; error_code: string | null; created_at: string;
};
type ThreadMessages = {
  thread: { id: string; title?: string | null };
  messages: Array<{ id: string; role: string; parts: Array<{ type?: string; toolName?: string; state?: string; output?: unknown; text?: string }> }>;
};
type SessionPayload = { id: string; name?: string | null; editor_state: unknown };

test.use({ channel: 'chrome', timezoneId: 'Asia/Shanghai', viewport: { width: 1440, height: 1000 },
  storageState: AUTH_STATE || undefined });
test.skip(!ENABLED, 'Set INK_REAL_SCHEDULED_TASK_QA=1 to run the named-account real scheduled-task journey.');

function diagnosticsFor(page: Page): string[] {
  const diagnostics: string[] = [];
  page.on('pageerror', (error) => diagnostics.push(`pageerror: ${error.message}`));
  page.on('console', (message) => {
    const text = message.text();
    if (message.type() === 'error' && !/(?:react-grab\.com|react-grab\.js|fonts\.googleapis\.com|fonts\.gstatic\.com)/.test(text)) {
      diagnostics.push(`console: ${text}`);
    }
  });
  page.on('requestfailed', (request) => {
    const url = request.url();
    if (request.failure()?.errorText !== 'net::ERR_ABORTED'
      && !/(?:react-grab\.com|react-grab\.js|fonts\.googleapis\.com|fonts\.gstatic\.com)/.test(url)) {
      diagnostics.push(`requestfailed: ${request.failure()?.errorText ?? 'failed'} ${new URL(url).pathname}`);
    }
  });
  page.on('response', (response) => {
    if (response.status() >= 400 && response.url().includes('/api/')) {
      diagnostics.push(`http ${response.status()}: ${new URL(response.url()).pathname}`);
    }
  });
  return diagnostics;
}

async function getJson<T>(request: APIRequestContext, path: string, csrfToken: string): Promise<T> {
  const response = await request.get(`${WEB_BASE}${path}`, { headers: { 'x-ink-csrf': csrfToken } });
  expect(response.status(), await response.text()).toBe(200);
  return response.json() as Promise<T>;
}

async function postJson<T>(request: APIRequestContext, path: string, csrfToken: string, data: unknown): Promise<T> {
  const response = await request.post(`${WEB_BASE}${path}`, {
    headers: {
      'x-ink-csrf': csrfToken,
      origin: WEB_BASE,
      referer: `${WEB_BASE}/`,
    },
    data,
  });
  expect(response.status(), await response.text()).toBe(200);
  return response.json() as Promise<T>;
}

function dateKeyInShanghai(): string {
  const parts = new Intl.DateTimeFormat('en-CA', {
    timeZone: 'Asia/Shanghai', year: 'numeric', month: '2-digit', day: '2-digit',
  }).formatToParts(new Date());
  const value = Object.fromEntries(parts.map((part) => [part.type, part.value]));
  return `${value.year}-${value.month}-${value.day}`;
}

test('Chat interval task writes the bound note without confirmation, exposes the run conversation, then edits to ten minutes and pauses', async ({ page }) => {
  test.setTimeout(480_000);
  mkdirSync(ARTIFACT_DIR, { recursive: true });
  await page.route('**/react-grab/**', async (route) => {
    await route.fulfill({ status: 200, contentType: 'application/javascript', body: '' });
  });
  const diagnostics = diagnosticsFor(page);
  if (!AUTH_STATE) throw new Error('INK_REAL_SCHEDULED_TASK_STORAGE_STATE must reference an existing normal public-login session.');
  const stamp = new Date().toISOString().replace(/[-:.TZ]/g, '').slice(0, 14);
  const taskTitle = `REAL-SCHEDULE-AUTO-E2E-${stamp}`;
  const noteSeed = `${taskTitle}\n这是一条真实定时任务自动写入验收笔记。`;
  const appendedMarker = `AUTO-SCHEDULE-NOTE-E2E-${stamp}`;
  let editorSessionId = '';

  const sessionResponse = await page.request.get(`${WEB_BASE}/auth/session`);
  expect(sessionResponse.status(), await sessionResponse.text()).toBe(200);
  const sessionPayload = await sessionResponse.json() as { csrf_token: string; user: { email: string } };
  expect(sessionPayload.user.email.toLowerCase()).toBe(ACTOR_EMAIL.toLowerCase());
  const csrfToken = sessionPayload.csrf_token;

  await page.goto(`${WEB_BASE}/story-workspace/writing`);
  const editor = page.getByPlaceholder('Start writing...');
  await expect(editor).toBeVisible({ timeout: 30_000 });
  await page.getByTitle('New Session').click();
  // New Session first persists the previous note, then replaces the Editor
  // state.  Filling before that asynchronous reset races with the blank load.
  await expect(editor).toHaveValue('', { timeout: 30_000 });
  await editor.fill(noteSeed);
  await expect(editor).toHaveValue(noteSeed);
  const saveResponsePromise = page.waitForResponse((response) => (
    response.request().method() === 'POST'
    && new URL(response.url()).pathname === '/api/sessions'
  ));
  await page.getByRole('button', { name: 'Save today' }).click();
  const saveResponse = await saveResponsePromise;
  expect(saveResponse.status()).toBe(200);
  const savedNote = saveResponse.request().postDataJSON() as {
    session_id?: string; editor_state?: unknown;
  };
  expect(JSON.stringify(savedNote.editor_state)).toContain(taskTitle);
  editorSessionId = String(savedNote.session_id ?? '');
  expect(editorSessionId).not.toBe('');
  await expect(page.getByText('Saved', { exact: true })).toBeVisible();

  await page.getByRole('button', { name: '对话', exact: true }).click();
  await page.waitForURL(/\/story-workspace\/chat/);
  const newChat = page.getByTitle(/^(New chat|新建对话)$/);
  if (await newChat.isVisible().catch(() => false)) await newChat.click();
  const input = page.getByRole('textbox', { name: /^(Chat input|聊天输入)$/ });
  await expect(input).toBeVisible({ timeout: 30_000 });
  const prompt = `请创建一个定时任务：标题为 ${taskTitle}，每隔 1 分钟执行一次，时区 Asia/Shanghai。每次执行时，只使用当前笔记工具在当前笔记末尾追加一行「${appendedMarker}」，不要删除或修改已有内容。创建完成后只回复任务已创建。`;
  await input.fill(prompt);
  const threadResponsePromise = page.waitForResponse((response) => (
    response.request().method() === 'POST' && new URL(response.url()).pathname === '/api/claude-agent/threads'
  ));
  const agentResponsePromise = page.waitForResponse((response) => (
    response.request().method() === 'POST' && new URL(response.url()).pathname === '/api/claude-agent'
  ));
  await page.getByRole('button', { name: /^(Send message|发送消息)$/ }).click();
  const threadResponse = await threadResponsePromise;
  expect(threadResponse.status()).toBe(200);
  const sourceThreadId = (await threadResponse.json() as { thread_id: string }).thread_id;
  const agentResponse = await agentResponsePromise;
  expect(agentResponse.status()).toBe(200);

  const marker = page.locator('.scheduled-task-marker').filter({ hasText: taskTitle });
  await expect(marker).toBeVisible({ timeout: 240_000 });
  await expect(marker).toContainText('每隔 1 分钟');
  await expect(page.getByRole('region', { name: '此对话创建的任务' })).toHaveCount(0);
  await marker.click();
  const detail = page.locator('.scheduled-task-detail');
  await expect(detail).toBeVisible();
  await expect(detail.locator('h3')).toHaveText(['任务信息', '会话', '任务周期']);
  await expect(detail).toContainText('创建任务的会话');
  await page.screenshot({ path: resolve(ARTIFACT_DIR, `${taskTitle}-chat-sidebar.png`), fullPage: true });

  const day = await getJson<{ tasks: ScheduledTask[]; triggers: ScheduledTrigger[] }>(
    page.request,
    `/api/claude-agent/scheduled-tasks/day?local_date=${dateKeyInShanghai()}&display_time_zone=Asia%2FShanghai`,
    csrfToken,
  );
  const created = day.tasks.find((task) => task.title === taskTitle);
  expect(created, `Scheduled task ${taskTitle} was not returned by the production day read.`).toBeDefined();
  expect(created).toMatchObject({ source_thread_id: sourceThreadId, status: 'active', revision: 1,
    rule: { kind: 'interval', interval_minutes: 1, time_zone: 'Asia/Shanghai' } });
  const taskId = created!.id;

  try {
    let settled: ScheduledTrigger | undefined;
    await expect.poll(async () => {
      expect(await page.locator('[role="alertdialog"]:visible').count(), 'Scheduled execution must not request browser confirmation.').toBe(0);
      const history = await getJson<{ triggers: ScheduledTrigger[] }>(
        page.request, `/api/claude-agent/scheduled-tasks/${encodeURIComponent(taskId)}/history?limit=20`, csrfToken,
      );
      settled = history.triggers.find((trigger) => ['succeeded', 'failed', 'state_unknown'].includes(trigger.status));
      return Boolean(settled);
    }, { timeout: 210_000, intervals: [2_000, 3_000, 5_000] }).toBe(true);
    expect(settled?.status, `Scheduled execution ended with ${settled?.error_code ?? 'no error code'}`).toBe('succeeded');
    expect(settled?.error_code).toBeNull();
    expect(settled?.target_thread_id).toBeTruthy();
    expect(settled?.final_message_id).toBeTruthy();

    const note = await getJson<SessionPayload>(page.request, `/api/sessions/${encodeURIComponent(editorSessionId)}`, csrfToken);
    expect(JSON.stringify(note.editor_state)).toContain(appendedMarker);
    const runHistory = await getJson<ThreadMessages>(
      page.request, `/api/claude-agent/threads/${encodeURIComponent(settled!.target_thread_id!)}/messages`, csrfToken,
    );
    const editorWriteParts = runHistory.messages.flatMap((message) => message.parts)
      .filter((part) => part.toolName === 'mcp__editor__write_segment');
    expect(editorWriteParts.length).toBeGreaterThan(0);
    expect(editorWriteParts.some((part) => part.state === 'output-available' || part.output !== undefined)).toBe(true);

    await detail.getByRole('button', { name: '关闭定时任务详情' }).click();
    await marker.click();
    await expect(detail.getByRole('button', { name: /任务运行会话/ })).toBeVisible();
    const targetMessagesPromise = page.waitForResponse((response) => (
      response.request().method() === 'GET'
      && new URL(response.url()).pathname === `/api/claude-agent/threads/${settled!.target_thread_id}/messages`
    ));
    await detail.getByRole('button', { name: /任务运行会话/ }).click();
    expect((await targetMessagesPromise).status()).toBe(200);
    await expect(page.locator(
      `[data-chat-message-id="${settled!.final_message_id}"]`,
    )).toContainText(appendedMarker, { timeout: 30_000 });

    const workspaceNavigation = page.getByRole('navigation', { name: 'Story Workspace 导航' });
    const moreNavigation = workspaceNavigation.getByRole('button', { name: '更多', exact: true });
    if (await moreNavigation.getAttribute('aria-expanded') !== 'true') await moreNavigation.click();
    await workspaceNavigation.getByRole('button', { name: '写作', exact: true }).click();
    await page.waitForURL(/\/story-workspace\/writing/);
    await expect(page.getByPlaceholder('Start writing...')).toHaveValue(new RegExp(appendedMarker));
    await page.getByRole('button', { name: 'Calendar' }).click();
    const taskCard = page.locator('.calendar-popup__task').filter({ hasText: taskTitle });
    await expect(taskCard).toBeVisible({ timeout: 30_000 });
    await taskCard.getByRole('button', { name: `编辑：${taskTitle}` }).click();
    const editDialog = page.getByRole('dialog', { name: `编辑“${taskTitle}”` });
    await expect(editDialog).toBeVisible();
    await editDialog.getByRole('button', { name: /高级日程/ }).click();
    const advancedSchedule = page.getByRole('dialog', { name: '高级日程', exact: true });
    await advancedSchedule.getByLabel('每隔（分钟）').fill('10');
    await advancedSchedule.getByRole('button', { name: '应用', exact: true }).click();
    const editResponsePromise = page.waitForResponse((response) => (
      response.request().method() === 'POST'
      && new URL(response.url()).pathname === `/api/claude-agent/scheduled-tasks/${taskId}/edit`
    ));
    await editDialog.getByRole('button', { name: '保存', exact: true }).click();
    expect((await editResponsePromise).status()).toBe(200);
    await expect(editDialog).toBeHidden();
    await expect(taskCard).toContainText('每隔 10 分钟');

    await taskCard.getByRole('button', { name: `更多操作：${taskTitle}` }).click();
    const pauseResponsePromise = page.waitForResponse((response) => (
      response.request().method() === 'POST'
      && new URL(response.url()).pathname === `/api/claude-agent/scheduled-tasks/${taskId}/pause`
    ));
    await page.getByRole('menuitem', { name: '暂停', exact: true }).click();
    expect((await pauseResponsePromise).status()).toBe(200);
    await expect(taskCard).toContainText('已暂停');
    await page.screenshot({ path: resolve(ARTIFACT_DIR, `${taskTitle}-calendar-paused.png`), fullPage: true });

    const finalTask = await getJson<{ task: ScheduledTask | null }>(
      page.request, `/api/claude-agent/scheduled-tasks/${encodeURIComponent(taskId)}`, csrfToken,
    );
    expect(finalTask.task).toMatchObject({ id: taskId, status: 'paused', revision: 3,
      rule: { kind: 'interval', interval_minutes: 10, time_zone: 'Asia/Shanghai' } });
    expect(diagnostics).toEqual([]);
    console.log(JSON.stringify({
      taskTitle, taskId, sourceThreadId, targetThreadId: settled!.target_thread_id,
      editorSessionId, triggerId: settled!.id, finalMessageId: settled!.final_message_id,
      finalStatus: finalTask.task?.status, finalRevision: finalTask.task?.revision,
    }));
  } finally {
    // Preserve all normal business records; stop recurring calls only for this exact newly created task.
    const current = await getJson<{ task: ScheduledTask | null }>(
      page.request, `/api/claude-agent/scheduled-tasks/${encodeURIComponent(taskId)}`, csrfToken,
    );
    if (current.task?.status === 'active') {
      await postJson(page.request, `/api/claude-agent/scheduled-tasks/${encodeURIComponent(taskId)}/pause`,
        csrfToken, { expected_revision: current.task.revision });
    }
  }
});
